"""Direct EN→ES translations for remaining clan quote texts."""

CLAN_DIRECT: dict[str, str] = {
    "Who thought {user} would become head? Nobody. Who is happy? Everyone.": "¿Quién pensó que {user} sería jefe? Nadie. ¿Quién está feliz? Todos.",
    "{user}, by tradition you should now buy everyone tea. But we are not insisting.": "{user}, por tradición ahora deberías invitar el té a todos. Pero no insistimos.",
    "Some look for meaning. {user} found it for a brief moment. Until midnight.": "Algunos buscan el sentido. {user} lo encontró por un instante. Hasta la medianoche.",
    "{user}, you are in the circle of clan honour. Do not fall — it is high up.": "{user}, estás en el círculo de honor del clan. No te caigas — está alto.",
    "{user}, you are the chosen one. If anything — it wears off by midnight.": "{user}, eres el elegido. Por si acaso — se pasa a la medianoche.",
    "AUF. The moon whispers the name {user}. Quietly, so as not to jinx.": "AUF. La luna susurra el nombre de {user}. Bajito, para no gafar.",
    "{user}, don't explain. Just act.": "{user}, no expliques. Solo actúa.",
    "First to rise is first to lead. {user} rose first.": "El primero en levantarse es el primero en liderar. {user} se levantó primero.",
    "{user}, being head isn't a title. It's character.": "{user}, ser jefe no es un título. Es carácter.",
    "Not everyone can lead. {user} can.": "No todos pueden liderar. {user} puede.",
    "{user}, you're not the best. You're the only one.": "{user}, no eres el mejor. Eres el único.",
    "{user}, being head isn't a privilege. It's a job.": "{user}, ser jefe no es un privilegio. Es un trabajo.",
    "The head's name — {user}. Remember it, if you haven't.": "El nombre del jefe — {user}. Recuérdalo, si no lo has hecho.",
    "{user}, you weren't picked by chance. There are no coincidences.": "{user}, no te eligieron por casualidad. No existen las coincidencias.",
    "{user}, you're at the top. Don't look down.": "{user}, estás en la cima. No mires abajo.",
    "{user}, great things start with one decision. Yours is made.": "{user}, las grandes cosas empiezan con una decisión. La tuya ya está tomada.",
    "{user}, you weren't asked. You were appointed. Feel the difference?": "{user}, no te preguntaron. Te nombraron. ¿Sientes la diferencia?",
    "{user}, no need to prove anything. Everyone already knows.": "{user}, no necesitas demostrar nada. Todos ya lo saben.",
    "{user}, the world around you is your clan. Protect it.": "{user}, el mundo a tu alrededor es tu clan. Protégelo.",
    "{user} took the helm. No unnecessary words.": "{user} tomó el mando. Sin palabras innecesarias.",
    "{user}, don't look for trouble — solve what's already there.": "{user}, no busques problemas — resuelve los que ya hay.",
    "Don't ask why {user}. Ask — why not sooner.": "No preguntes por qué {user}. Pregunta — por qué no antes.",
    "{user}, reputation is everything. Yours — spotless.": "{user}, la reputación lo es todo. La tuya — impecable.",
    "Some lead. Some follow. {user} leads.": "Unos lideran. Otros siguen. {user} lidera.",
    "{user}, iron will — iron clan.": "{user}, voluntad de hierro — clan de hierro.",
    "{user}, you came, you saw, you led.": "{user}, llegaste, viste, lideraste.",
    "When {user} is at the helm, no storm is scary.": "Cuando {user} está al mando, ninguna tormenta da miedo.",
    "{user}, you don't need a plan. You are the plan.": "{user}, no necesitas un plan. Tú eres el plan.",
    "{user}, you're not here for applause. You're here for business.": "{user}, no estás aquí por los aplausos. Estás aquí por los resultados.",
    "{user}, business first. Everything else — later.": "{user}, primero lo importante. Todo lo demás — después.",
    "{user}, every strike — precise. Every decision — right.": "{user}, cada golpe — preciso. Cada decisión — correcta.",
    "The RNG said: {user}. The RNG doesn't lie. Probably.": "El RNG dijo: {user}. El RNG no miente. Probablemente.",
    "{user}, how does it feel at the top? Don't answer, we already know.": "{user}, ¿cómo se siente en la cima? No respondas, ya lo sabemos.",
    "New head: {user}. Update 1.0.1. Bug fixes in the next patch.": "Nuevo jefe: {user}. Actualización 1.0.1. Correcciones de bugs en el próximo parche.",
    "Who's head? {user}. Who asked? Nobody. We announced it ourselves.": "¿Quién es jefe? {user}. ¿Quién preguntó? Nadie. Lo anunciamos nosotros.",
    "Clan: 'Who'll be head?' Random: '{user}'. Clan: 'Well ok'.": "Clan: '¿Quién será jefe?' Random: '{user}'. Clan: 'Bueno ok'.",
    "New head — {user}. No nerfs planned yet.": "Nuevo jefe — {user}. Sin nerfs planeados todavía.",
    "Head {user} entered the chat. Everyone froze. Then resumed memeing.": "Jefe {user} entró al chat. Todos se congelaron. Luego siguieron con los memes.",
    "404: another head not found. {user} is the only option.": "404: otro jefe no encontrado. {user} es la única opción.",
    "{user}, the strong don't shout. They just stand in front.": "{user}, los fuertes no gritan. Simplemente se paran al frente.",
    "Some dream, some act. {user} is one who acts.": "Unos sueñan, otros actúan. {user} es de los que actúan.",
    "Life gave {user} a chance. {user} didn't ask twice.": "La vida le dio una oportunidad a {user}. {user} no preguntó dos veces.",
    "{user} — choice of the day. Don't look for a catch — there isn't one.": "{user} — elección del día. No busques truco — no lo hay.",
    "{user}, be humble and people will follow. You're already humble. Kidding, you're awesome.": "{user}, sé humilde y la gente te seguirá. Ya eres humilde. Es broma, eres genial.",
    "A real head doesn't brag. {user} is real.": "Un jefe de verdad no presume. {user} es de verdad.",
    "While someone waited for a sign, {user} became the sign.": "Mientras alguien esperaba una señal, {user} se convirtió en la señal.",
    "Being head isn't a title, it's a state of mind. {user} has it.": "Ser jefe no es un título, es un estado mental. {user} lo tiene.",
    "Those who didn't believe in {user} — reconsider your views.": "Los que no creyeron en {user} — reconsideren sus opiniones.",
    "When you're chosen — it means people believe in you. {user}, they believe.": "Cuando te eligen — significa que creen en ti. {user}, creen en ti.",
    "{user}, don't forget where you're from. But don't forget where you're going.": "{user}, no olvides de dónde vienes. Pero no olvides a dónde vas.",
    "Became head — now you step up. {user}, lead on.": "Te hiciste jefe — ahora da el paso. {user}, adelante.",
    "The one who's quiet knows more. {user} knows the most.": "El que calla sabe más. {user} sabe lo máximo.",
    "The head isn't the one who wants it. It's the one who's wanted. {user} — that one.": "Jefe no es el que quiere. Es al que quieren. {user} — ese mero.",
    "The head isn't the one in front. It's the one others follow. They follow {user}.": "Jefe no es el que va al frente. Es al que los demás siguen. Siguen a {user}.",
    "{user}'s time. Don't rush it — it knows when to come.": "El momento de {user}. No lo apures — él sabe cuándo llegar.",
    "Wolves don't vote. Wolves choose the strongest. Chose {user}. AUF.": "Los lobos no votan. Los lobos eligen al más fuerte. Eligieron a {user}. AUF.",
    "{user}, the forest belongs to you. Until dawn. AUF. 🐺": "{user}, el bosque es tuyo. Hasta el amanecer. AUF. 🐺",
    "Silence in the forest. {user} is on the hunt. AUF.": "Silencio en el bosque. {user} está de cacería. AUF.",
    "AUF! Darkness retreats when {user} is on guard.": "¡AUF! La oscuridad retrocede cuando {user} está de guardia.",
    "When {user} steps out, even the wind goes quiet. AUF. 🐺": "Cuando {user} sale, hasta el viento se calla. AUF. 🐺",
    "The moon sees all. The moon sees {user}. The moon approves. AUF. 🐺": "La luna lo ve todo. La luna ve a {user}. La luna aprueba. AUF. 🐺",
    "When the moon calls, {user} answers first. AUF. 🐺": "Cuando la luna llama, {user} responde primero. AUF. 🐺",
    "{user}, the moon lights your path. Walk with confidence. AUF.": "{user}, la luna ilumina tu camino. Camina con confianza. AUF.",
    "Dark forest, full moon, {user} in front. AUF. 🐺": "Bosque oscuro, luna llena, {user} al frente. AUF. 🐺",
    "{user}, walk straight. Don't turn.": "{user}, camina derecho. No voltees.",
    "Head isn't a word. It's {user}.": "Jefe no es una palabra. Es {user}.",
    "{user}, confidence isn't born. It's earned.": "{user}, la confianza no se nace con ella. Se gana.",
    "When {user} is silent — it's louder than any words.": "Cuando {user} calla — es más fuerte que cualquier palabra.",
    "{user}, the head doesn't ask permission.": "{user}, el jefe no pide permiso.",
    "You don't need the crowd's approval, {user}. You need a goal.": "No necesitas la aprobación del público, {user}. Necesitas una meta.",
    "{user}, what matters is the result. The rest is noise.": "{user}, lo que importa es el resultado. Lo demás es ruido.",
    "{user}, be tough when needed. Soft — never.": "{user}, sé duro cuando haga falta. Blando — nunca.",
    "{user}, the head goes in first and leaves last.": "{user}, el jefe entra primero y sale último.",
    "Every step by {user} is a step for the whole clan.": "Cada paso de {user} es un paso para todo el clan.",
    "{user}, honour is what money can't buy. But you can wear it.": "{user}, el honor es lo que el dinero no compra. Pero puedes llevarlo.",
    "{user}, when you lead — nobody falls behind.": "{user}, cuando tú lideras — nadie se queda atrás.",
    "Head {user} — a guarantee of order.": "Jefe {user} — garantía de orden.",
    "{user}, you don't look for excuses. You look for solutions.": "{user}, no buscas excusas. Buscas soluciones.",
    "{user}, being head isn't a reward. It's a test. You're ready.": "{user}, ser jefe no es un premio. Es una prueba. Estás listo.",
    "{user}, it doesn't matter how long you're at the helm. It matters how.": "{user}, no importa cuánto tiempo estés al mando. Importa cómo.",
    "{user}, don't turn around — ahead there's only the road.": "{user}, no mires atrás — adelante solo hay camino.",
    "Head {user} — not one extra word, not one step back.": "Jefe {user} — ni una palabra de más, ni un paso atrás.",
    "{user}, calm before the storm. And the storm is you.": "{user}, calma antes de la tormenta. Y la tormenta eres tú.",
    "{user}, one day — one chance. Use it.": "{user}, un día — una oportunidad. Úsala.",
    "{user}, the head doesn't complain. The head resolves.": "{user}, el jefe no se queja. El jefe resuelve.",
    "{user}, every second is a chance to prove it. Prove it.": "{user}, cada segundo es una oportunidad de demostrarlo. Demuéstralo.",
    "{user}, you're not head for a day. You're head of this day.": "{user}, no eres jefe por un día. Eres el jefe de este día.",
    "Order restored. {user} — at the helm.": "Orden restaurado. {user} — al mando.",
    "Head: {user}. Trust rating: 146%. Margin of error: irrelevant.": "Jefe: {user}. Índice de confianza: 146%. Margen de error: irrelevante.",
    "Who's head? {user}. Next question. No, really, next question.": "¿Quién es jefe? {user}. Siguiente pregunta. No, en serio, siguiente pregunta.",
    "New head — {user}. System requirements: 0 skills, 100% luck.": "Nuevo jefe — {user}. Requisitos del sistema: 0 habilidades, 100% suerte.",
    "Head {user} entered the chat. Chat: *applauds*. Quietly.": "Jefe {user} entró al chat. Chat: *aplaude*. Bajito.",
    "Someone ordered a head? Delivery: {user}. Courier: random.": "¿Alguien pidió un jefe? Entrega: {user}. Mensajero: random.",
    "Head: {user}. Update released without bugs. For once.": "Jefe: {user}. Actualización sin bugs. Por primera vez.",
    "{user}, in this clan you're loved. Don't abuse it.": "{user}, en este clan te quieren. No abuses.",
    "{user}, be someone who's trusted. You're already trusted.": "{user}, sé alguien en quien se confíe. Ya confían en ti.",
    "Head {user} — that's when everything's in its place.": "Jefe {user} — es cuando todo está en su lugar.",
    "The head leads even when they don't know where. {user}, lead.": "El jefe lidera incluso cuando no sabe a dónde. {user}, lidera.",
    "{user}, this clan believes in you. The rest — details.": "{user}, este clan cree en ti. Lo demás — detalles.",
    "AUF! The forest is silent — {user} is on the trail. 🐺": "¡AUF! El bosque calla — {user} está en la pista. 🐺",
    "AUF! When {user} leads, even shadows obey.": "¡AUF! Cuando {user} lidera, hasta las sombras obedecen.",
    "AUF! {user} — the one heard beyond the horizon.": "¡AUF! {user} — al que se escucha más allá del horizonte.",
    "Full moon. Pack. {user}. Everything as it should be. AUF.": "Luna llena. Manada. {user}. Todo como debe ser. AUF.",
    "{user}, don't fear the dark — you are the dark. AUF. 🐺": "{user}, no le temas a la oscuridad — tú eres la oscuridad. AUF. 🐺",
    "AUF! {user} — a growl in the night. Nobody argues.": "¡AUF! {user} — un gruñido en la noche. Nadie discute.",
    "AUF! {user} — an echo in the mountains. Loud and confident.": "¡AUF! {user} — un eco en las montañas. Fuerte y seguro.",
    "Moonlight, snowy trail, {user} in front. AUF. 🐺": "Luz de luna, sendero nevado, {user} al frente. AUF. 🐺",
    "AUF! {user} — the one the moon chose.": "¡AUF! {user} — al que la luna eligió.",
    "The full moon lights {user}'s way. AUF. 🐺": "La luna llena ilumina el camino de {user}. AUF. 🐺",
    "{user}, a real head is the one who stands for their own.": "{user}, un jefe de verdad es el que da la cara por los suyos.",
    "{user}, be like a rock — firm and reliable.": "{user}, sé como una roca — firme y confiable.",
    "{user}, don't be afraid of heights. You're already there.": "{user}, no le tengas miedo a las alturas. Ya estás ahí.",
    "{user}, you're not alone. Behind you — the whole clan.": "{user}, no estás solo. Detrás de ti — todo el clan.",
    "Head {user}. No fuss, no rush. Our way.": "Jefe {user}. Sin drama, sin prisa. A nuestro modo.",
    "Head: {user}. Review: 'Masterpiece. Watching for the third time'.": "Jefe: {user}. Reseña: 'Obra maestra. Viéndola por tercera vez'.",
    "AUF! The night belongs to {user}. So does the day. 🐺": "¡AUF! La noche pertenece a {user}. Y el día también. 🐺",
    "AUF! {user} — silver in the moonlight.": "¡AUF! {user} — plata bajo la luz de luna.",
    "Stars gaze at {user}. The moon nods. AUF. 🐺": "Las estrellas miran a {user}. La luna asiente. AUF. 🐺",
    "Head {user} walked into a bar. Bartender says: 'The usual?' {user} nods.": "Jefe {user} entró a un bar. El cantinero dice: '¿Lo de siempre?' {user} asiente.",
    "If {user} were a pizza, they'd be a head-pizza. With double cheese.": "Si {user} fuera una pizza, sería una pizza-jefe. Con doble queso.",
    "Head {user}. Pigeons in the square bowed. Or were just eating bread.": "Jefe {user}. Las palomas de la plaza hicieron reverencia. O solo comían pan.",
    "Head {user}. Even spam emails now start with 'Dear Head'.": "Jefe {user}. Hasta los correos de spam ahora empiezan con 'Estimado Jefe'.",
    "Head {user}. Followers increased. Oh wait, no followers. But the feeling is there.": "Jefe {user}. Los seguidores aumentaron. Ah espera, no hay seguidores. Pero la sensación está.",
    "Head {user}. Netflix offered a movie deal.": "Jefe {user}. Netflix ofreció un contrato de película.",
    "Head {user}. All chat messages now start with 'Your Majesty'.": "Jefe {user}. Todos los mensajes del chat ahora empiezan con 'Su Majestad'.",
    "Head {user}. If life were a game, this would be the immortality cheat code.": "Jefe {user}. Si la vida fuera un juego, esto sería el código de inmortalidad.",
    "Head {user}. Antivirus approved: 'No threats. Only greatness'.": "Jefe {user}. El antivirus aprobó: 'Sin amenazas. Solo grandeza'.",
    "Congrats {user}. Well, somebody had to.": "Felicidades {user}. Bueno, alguien tenía que hacerlo.",
    "Head {user}. Not the worst option. Far from the best. But definitely not the worst.": "Jefe {user}. No es la peor opción. Lejos de la mejor. Pero definitivamente no la peor.",
    "Head {user}. No panic. It's just for one day. We'll survive.": "Jefe {user}. Sin pánico. Es solo por un día. Sobreviviremos.",
    "Head {user}. Welcome them. Or don't. They're here anyway.": "Jefe {user}. Dénle la bienvenida. O no. De todas formas ya está aquí.",
    "Head {user}. You can exhale. Or not. Depends on {user}.": "Jefe {user}. Pueden exhalar. O no. Depende de {user}.",
    "Head {user}. Yay? Yay. Probably. Yes, yay.": "Jefe {user}. ¿Yay? Yay. Probablemente. Sí, yay.",
    "Head {user}. Questions? No questions. Correct.": "Jefe {user}. ¿Preguntas? Sin preguntas. Correcto.",
    "{user} took the helm. Mutiny? Suppressed. Questions? Closed.": "{user} tomó el mando. ¿Motín? Suprimido. ¿Preguntas? Cerradas.",
    "Head {user}. The weak are asked not to disturb.": "Jefe {user}. A los débiles se les pide no molestar.",
    "{user} rules. You can challenge it. Surviving after — harder.": "{user} manda. Puedes cuestionarlo. Sobrevivir después — más difícil.",
    "{user} stepped up to lead. Those who didn't make it — too late.": "{user} dio el paso para liderar. Los que no llegaron — muy tarde.",
    "Head {user}. Softness is over. Hardness begins.": "Jefe {user}. Se acabó la suavidad. Empieza la dureza.",
    "Head {user}. Whispers behind the back? Will end quickly.": "Jefe {user}. ¿Susurros a la espalda? Terminarán rápido.",
    "{user} is at the helm. Whoever's in the way — clears out.": "{user} está al mando. El que se atraviese — se quita.",
    "Head {user}. Rules are simple: obey or vanish.": "Jefe {user}. Las reglas son simples: obedece o desaparece.",
    "AUF! {user} — THE LEADER! THE MOON EXPLODED! NO WAIT, IT'S STILL THERE! 🐺": "¡AUF! ¡{user} — EL LÍDER! ¡LA LUNA EXPLOTÓ! ¡NO ESPERA, AÚN ESTÁ AHÍ! 🐺",
    "{user} — ALPHA! Pack is running! Where — doesn't matter! Main thing — behind {user}! AUF! 🐺": "¡{user} — ALFA! ¡La manada corre! ¡A dónde — no importa! ¡Lo importante — detrás de {user}! ¡AUF! 🐺",
    "AUF-AUF-AUF! {user}! LEADER! I can't stop! AUF! 🐺🐺🐺": "¡AUF-AUF-AUF! ¡{user}! ¡LÍDER! ¡No puedo parar! ¡AUF! 🐺🐺🐺",
    "AUF! MOON IS RED! {user} — RED LEADER! RED MEANS POWER! 🐺": "¡AUF! ¡LA LUNA ESTÁ ROJA! ¡{user} — LÍDER ROJO! ¡ROJO SIGNIFICA PODER! 🐺",
    "{user} — ALPHA! OMEGA! BETA! ALL LETTERS AT ONCE! AUF! 🐺": "¡{user} — ALFA! ¡OMEGA! ¡BETA! ¡TODAS LAS LETRAS A LA VEZ! ¡AUF! 🐺",
    "AUF! {user} — WOLF-HURRICANE! WOLF-TORNADO! WOLF-TSUNAMI! 🐺🌊": "¡AUF! ¡{user} — LOBO-HURACÁN! ¡LOBO-TORNADO! ¡LOBO-TSUNAMI! 🐺🌊",
    "AUF! MOON FELL! NO! MOON IS JUMPING WITH JOY FOR {user}! 🐺": "¡AUF! ¡LA LUNA CAYÓ! ¡NO! ¡LA LUNA SALTA DE ALEGRÍA POR {user}! 🐺",
    "AUF! {user} — WOLF! MEGA-WOLF! GIGA-WOLF! TERA-WOLF! 🐺🐺🐺": "¡AUF! ¡{user} — LOBO! ¡MEGA-LOBO! ¡GIGA-LOBO! ¡TERA-LOBO! 🐺🐺🐺",
    "AUF! {user} — HEAD! HOWLING IN ALL FOUR DIRECTIONS! AND UP! AND DOWN! 🐺": "¡AUF! ¡{user} — JEFE! ¡AULLANDO EN LAS CUATRO DIRECCIONES! ¡Y ARRIBA! ¡Y ABAJO! 🐺",
    "{user} — HEAD! I've been running in circles for an hour! Can't stop! HELP! AUF! 🐺": "¡{user} — JEFE! ¡Llevo una hora corriendo en círculos! ¡No puedo parar! ¡AYUDA! ¡AUF! 🐺",
    "AUF! TRIPLE AUF! QUADRUPLE! {user} — LEADER! MATH IS BROKEN! 🐺": "¡AUF! ¡TRIPLE AUF! ¡CUÁDRUPLE! ¡{user} — LÍDER! ¡LAS MATES SE ROMPIERON! 🐺",
    "AUF! {user} — A WOLF AMONG WOLVES AMONG WOLVES! RECURSIVE WOLF! 🐺": "¡AUF! ¡{user} — UN LOBO ENTRE LOBOS ENTRE LOBOS! ¡LOBO RECURSIVO! 🐺",
    "{user} — ALPHA! Teeth chattering from delight! Or from cold! Doesn't matter! AUF! 🐺": "¡{user} — ALFA! ¡Los dientes castañean de alegría! ¡O de frío! ¡No importa! ¡AUF! 🐺",
    "{user} — HEAD! Pack in ecstasy! What is ecstasy? Doesn't matter! AUF! 🐺": "¡{user} — JEFE! ¡La manada en éxtasis! ¿Qué es éxtasis? ¡No importa! ¡AUF! 🐺",
    "{user} — HEAD! Gravity cancelled! Pack is flying! No, running! No, HOWLING! AUF! 🐺": "¡{user} — JEFE! ¡Gravedad cancelada! ¡La manada vuela! ¡No, corre! ¡No, AÚLLA! ¡AUF! 🐺",
    "AUF! {user} — GOD-TIER WOLF! What? Yes! AUF! YES! 🐺": "¡AUF! ¡{user} — LOBO NIVEL DIOS! ¿Qué? ¡Sí! ¡AUF! ¡SÍ! 🐺",
    "AUF! {user} — HEAD! I'm running! Where? TO THE MOON! Why? BECAUSE AUF! 🐺": "¡AUF! ¡{user} — JEFE! ¡Estoy corriendo! ¿A dónde? ¡A LA LUNA! ¿Por qué? ¡PORQUE AUF! 🐺",
    "{user} — ALPHA-ULTRA-MEGA-LEADER! Long word! But {user} is longer! AUF! 🐺": "¡{user} — ALFA-ULTRA-MEGA-LÍDER! ¡Palabra larga! ¡Pero {user} es más largo! ¡AUF! 🐺",
    "{user} — HEAD! FIVE MOONS! No, one! But it's HUGE! LIKE {user}! AUF! 🐺": "¡{user} — JEFE! ¡CINCO LUNAS! ¡No, una! ¡Pero es ENORME! ¡COMO {user}! ¡AUF! 🐺",
    "{user} — ALPHA! Time stopped! No, sped up! No, got confused! AUF! 🐺": "¡{user} — ALFA! ¡El tiempo se detuvo! ¡No, se aceleró! ¡No, se confundió! ¡AUF! 🐺",
    "AUF! {user} — EARTHQUAKE-WOLF! Tectonic plates shifted! By a millimetre! But still! 🐺": "¡AUF! ¡{user} — LOBO-TERREMOTO! ¡Las placas tectónicas se movieron! ¡Un milímetro! ¡Pero igual! 🐺",
    "AUF! {user} — HEAD! SEVEN RAINBOWS! SIMULTANEOUSLY! AT NIGHT! HOW?! DOESN'T MATTER! 🐺": "¡AUF! ¡{user} — JEFE! ¡SIETE ARCOÍRIS! ¡SIMULTÁNEOS! ¡DE NOCHE! ¡¿CÓMO?! ¡NO IMPORTA! 🐺",
    "{user} — ALPHA! Volcano woke up! From joy! Lava is warm! Like our feelings! AUF! 🐺": "¡{user} — ALFA! ¡El volcán despertó! ¡De alegría! ¡La lava es cálida! ¡Como nuestros sentimientos! ¡AUF! 🐺",
    "AUF! {user} — MEGA-ALPHA! The ocean parted! No! It's a puddle! But POWERFUL! 🐺": "¡AUF! ¡{user} — MEGA-ALFA! ¡El océano se partió! ¡No! ¡Es un charco! ¡Pero PODEROSO! 🐺",
    "AUF! {user} — HEAD! I'M BITING THE AIR FROM EXCITEMENT! AIR TASTES BAD! BUT AUF! 🐺": "¡AUF! ¡{user} — JEFE! ¡ESTOY MORDIENDO EL AIRE DE EMOCIÓN! ¡EL AIRE SABE FEO! ¡PERO AUF! 🐺",
    "{user} — ALPHA-WOLF-EMPEROR! That title didn't exist! Now it does! AUF! 🐺": "¡{user} — ALFA-LOBO-EMPERADOR! ¡Ese título no existía! ¡Ahora sí! ¡AUF! 🐺",
    "AUF! {user} — LEADER OF LEADERS OF LEADERS! HOW MANY LEVELS? INFINITY! 🐺": "¡AUF! ¡{user} — LÍDER DE LÍDERES DE LÍDERES! ¡¿CUÁNTOS NIVELES?! ¡INFINITO! 🐺",
    "Head {user}. The courier arrived before the estimated time. First time in history.": "Jefe {user}. El repartidor llegó antes de la hora estimada. Primera vez en la historia.",
    "Head {user}. USB went in on the first try. First. Try.": "Jefe {user}. El USB entró al primer intento. Primer. Intento.",
    "Head {user}. Umbrella not forgotten at home. Rain didn't come. Perfect.": "Jefe {user}. El paraguas no se olvidó en casa. No llovió. Perfecto.",
    "Head {user}. Egg cracked perfectly. No shell in the pan.": "Jefe {user}. El huevo se rompió perfecto. Sin cáscara en el sartén.",
    "Head {user}. Ice cream didn't drip on the shirt. Day of miracles.": "Jefe {user}. El helado no goteó en la camisa. Día de milagros.",
    "Head {user}. Doorbell works. From the first press. Unique.": "Jefe {user}. El timbre funciona. Al primer toque. Único.",
    "Head {user}. Well, at least not for long.": "Jefe {user}. Bueno, al menos no será por mucho.",
    "Head {user}. Rating: 5 out of 10. For effort — 7.": "Jefe {user}. Calificación: 5 de 10. Por esfuerzo — 7.",
    "Head {user}. Your dissatisfaction interests no one.": "Jefe {user}. Tu descontento no le interesa a nadie.",
    "Head {user}. No, it's not up for discussion. No, your opinion is not considered.": "Jefe {user}. No, no se discute. No, tu opinión no se considera.",
    "{user} rules. Quietly. Firmly. Without unnecessary words.": "{user} manda. En silencio. Con firmeza. Sin palabras innecesarias.",
    "Head {user}. They're not angry. They're fair. But better not test it.": "Jefe {user}. No está enojado. Es justo. Pero mejor no lo pruebes.",
    "Head {user}. Whispers? Conspiracy? Forget it. {user} hears everything.": "Jefe {user}. ¿Susurros? ¿Conspiración? Olvídalo. {user} lo escucha todo.",
    "AUF! {user} — LEADER! THEY TOLD ME TO CALM DOWN! I CAN'T! AUF! 🐺": "¡AUF! ¡{user} — LÍDER! ¡ME DIJERON QUE ME CALMARA! ¡NO PUEDO! ¡AUF! 🐺",
    "{user} — ALPHA! EIGHT MOONS! I COUNTED! MAYBE NINE! AUF! 🐺🐺": "¡{user} — ALFA! ¡OCHO LUNAS! ¡LAS CONTÉ! ¡QUIZÁ NUEVE! ¡AUF! 🐺🐺",
    "{user} — HEAD! EARTH FLIPPED! No! I flipped! FROM JOY! AUF! 🐺": "¡{user} — JEFE! ¡LA TIERRA DIO VUELTA! ¡No! ¡Yo di vuelta! ¡DE ALEGRÍA! ¡AUF! 🐺",
    "AUF! {user} — WOLF! PACK IS RUNNING! WHERE — ONLY {user} KNOWS! WE TRUST! 🐺": "¡AUF! ¡{user} — LOBO! ¡LA MANADA CORRE! ¡A DÓNDE — SOLO {user} SABE! ¡CONFIAMOS! 🐺",
    "AUF! {user} — ALPHA! I'M SCREAMING SO LOUD THE NEIGHBOURS STARTED SCREAMING AUF TOO! 🐺": "¡AUF! ¡{user} — ALFA! ¡GRITO TAN FUERTE QUE LOS VECINOS EMPEZARON A GRITAR AUF TAMBIÉN! 🐺",
    "{user} — HEAD! VOLCANO ERUPTING! No, it's the kettle! But SYMBOLIC! AUF! 🐺": "¡{user} — JEFE! ¡VOLCÁN EN ERUPCIÓN! ¡No, es la tetera! ¡Pero SIMBÓLICO! ¡AUF! 🐺",
    "{user} — ALPHA! Squirrels in the trees applaud! With nuts! AUF! 🐺": "¡{user} — ALFA! ¡Las ardillas en los árboles aplauden! ¡Con nueces! ¡AUF! 🐺",
    "AUF! {user} — MEGALEADER-TURBO-PLUS! That plan doesn't exist! Now it does! 🐺": "¡AUF! ¡{user} — MEGALÍDER-TURBO-PLUS! ¡Ese plan no existía! ¡Ahora sí! 🐺",
    "{user} — HEAD! Meteors swerved! They fear {user}! Or gravity! DOESN'T MATTER! AUF! 🐺": "¡{user} — JEFE! ¡Los meteoros se desviaron! ¡Le temen a {user}! ¡O a la gravedad! ¡NO IMPORTA! ¡AUF! 🐺",
    "{user} — ALPHA! PACK LOST ITS VOICE! FOUND IT! LOST IT AGAIN! AUF! 🐺": "¡{user} — ALFA! ¡LA MANADA PERDIÓ LA VOZ! ¡LA ENCONTRÓ! ¡LA PERDIÓ DE NUEVO! ¡AUF! 🐺",
    "AUF! {user} — GALAXY LEADER! WHICH GALAXY? OURS! THERE'S NO OTHER! THERE IS! BUT OURS! 🐺": "¡AUF! ¡{user} — LÍDER GALÁCTICO! ¡¿QUÉ GALAXIA?! ¡LA NUESTRA! ¡NO HAY OTRA! ¡SÍ HAY! ¡PERO LA NUESTRA! 🐺",
    "{user} — HEAD! I FELL! GOT UP! FELL AGAIN! FROM EXCITEMENT! AUF! 🐺": "¡{user} — JEFE! ¡ME CAÍ! ¡ME LEVANTÉ! ¡ME CAÍ DE NUEVO! ¡DE EMOCIÓN! ¡AUF! 🐺",
    "{user} — ALPHA! THUNDER FROM CLEAR SKY! THAT'S THE PACK APPLAUDING! WITH PAWS! AUF! 🐺": "¡{user} — ALFA! ¡TRUENO EN CIELO DESPEJADO! ¡ES LA MANADA APLAUDIENDO! ¡CON LAS PATAS! ¡AUF! 🐺",
    "AUF! {user} — LEADER! MY HEART BEATS SO FAST THE CARDIOLOGIST IS WORRIED! 🐺": "¡AUF! ¡{user} — LÍDER! ¡MI CORAZÓN LATE TAN RÁPIDO QUE EL CARDIÓLOGO ESTÁ PREOCUPADO! 🐺",
    "{user} — HEAD! TEN WOLVES HOWL! HUNDRED! THOUSAND! THE WHOLE WORLD! AUF! 🐺🐺🐺": "¡{user} — JEFE! ¡DIEZ LOBOS AÚLLAN! ¡CIEN! ¡MIL! ¡EL MUNDO ENTERO! ¡AUF! 🐺🐺🐺",
    "{user} — ALPHA! SUN ROSE TWICE! No, once! But BRIGHT! LIKE {user}! AUF! 🐺": "¡{user} — ALFA! ¡EL SOL SALIÓ DOS VECES! ¡No, una! ¡Pero BRILLANTE! ¡COMO {user}! ¡AUF! 🐺",
    "AUF! {user} — LEADER! PACK SO HAPPY IT FORGOT WHY IT'S HOWLING! BUT CONTINUES! 🐺": "¡AUF! ¡{user} — LÍDER! ¡LA MANADA TAN FELIZ QUE OLVIDÓ POR QUÉ AÚLLA! ¡PERO SIGUE! 🐺",
    "{user} — HEAD! EVERY CELL IN MY BODY SCREAMS AUF! EVEN THOSE THAT CAN'T! 🐺": "¡{user} — JEFE! ¡CADA CÉLULA DE MI CUERPO GRITA AUF! ¡HASTA LAS QUE NO PUEDEN! 🐺",
    "{user} — ALPHA! THEY TOLD ME TO TYPE QUIETER! BUT HOW?! {user} — LEADER! AUF! 🐺🐺🐺": "¡{user} — ALFA! ¡ME DIJERON QUE ESCRIBA MÁS BAJO! ¡¿PERO CÓMO?! ¡{user} — LÍDER! ¡AUF! 🐺🐺🐺",
    "AUF! {user} — HEAD! I'VE BEEN HOWLING SO LONG I FORGOT MY NORMAL VOICE! 🐺": "¡AUF! ¡{user} — JEFE! ¡LLEVO TANTO AULLANDO QUE OLVIDÉ MI VOZ NORMAL! 🐺",
    "{user} — LEADER! TECTONIC PLATES DANCING! TO THE RHYTHM OF AUF! GEOLOGISTS CRYING! 🐺": "¡{user} — LÍDER! ¡PLACAS TECTÓNICAS BAILANDO! ¡AL RITMO DE AUF! ¡GEÓLOGOS LLORANDO! 🐺",
    "AUF! {user} — ALPHA! QUANTUM PHYSICS BROKE! {user} IS SIMULTANEOUSLY LEADER AND SUPERLEADER! 🐺": "¡AUF! ¡{user} — ALFA! ¡LA FÍSICA CUÁNTICA SE ROMPIÓ! ¡{user} ES SIMULTÁNEAMENTE LÍDER Y SUPERLÍDER! 🐺",
    "{user} — HEAD! THAT'S IT! NOTHING MORE TO SAY! EXCEPT AUF! AUF! AUF! AUF! 🐺🐺🐺🐺": "¡{user} — JEFE! ¡ESO ES TODO! ¡NADA MÁS QUE DECIR! ¡EXCEPTO AUF! ¡AUF! ¡AUF! ¡AUF! 🐺🐺🐺🐺",
    "Head {user}. The janitor swept the yard. In honour of the event.": "Jefe {user}. El conserje barrió el patio. En honor al evento.",
    "Head {user}. Mosquito didn't bite. Not one. All evening.": "Jefe {user}. Ningún mosquito picó. Ni uno. Toda la noche.",
    "Head {user}. Curtain didn't jam. Blinds raised evenly. Magic.": "Jefe {user}. La cortina no se atoró. Las persianas subieron parejo. Magia.",
    "Head {user}. Pizza cut evenly. All slices the same.": "Jefe {user}. La pizza se cortó parejo. Todas las rebanadas iguales.",
    "Head {user}. We've survived worse.": "Jefe {user}. Hemos sobrevivido cosas peores.",
    "Head {user}. Trust level: 'cautious optimism'.": "Jefe {user}. Nivel de confianza: 'optimismo cauteloso'.",
    "Head {user}. Was it better? No. Will it be? Possibly. Now? Tolerable.": "Jefe {user}. ¿Era mejor antes? No. ¿Será mejor? Posiblemente. ¿Ahora? Tolerable.",
    "Head {user}. The weak leave. The strong stay. Choose.": "Jefe {user}. Los débiles se van. Los fuertes se quedan. Elige.",
    "Head {user}. Those who came to argue — left silently.": "Jefe {user}. Los que vinieron a discutir — se fueron en silencio.",
}
