"""Direct EN→ES translations for remaining oracle texts."""

ORACLE_DIRECT: dict[str, str] = {
    "The pipirik sage forecasts: by month's end you'll hit a personal record, {user}.": "El sabio pipirik pronostica: a fin de mes alcanzarás un récord personal, {user}.",
    "Flip the pillow — find an idea, {user}.": "Voltea la almohada — encuentra una idea, {user}.",
    "Today wear mismatched socks, {user} — it works.": "Hoy usa calcetines disparejos, {user} — funciona.",
    "{user}, check your pockets. Something's there.": "{user}, revisa tus bolsillos. Hay algo ahí.",
    "If you meet a pigeon — nod, {user}. It's a pipirik scout.": "Si te encuentras una paloma — asiente, {user}. Es un explorador pipirik.",
    "{user}, check the remote's batteries. Just saying.": "{user}, revisa las pilas del control. Solo digo.",
    "The reading: ahead lies a field of possibilities, {user}.": "La lectura: adelante hay un campo de posibilidades, {user}.",
    "Powers of the pipirik come to you, {user}. Receive them with thanks.": "Los poderes del pipirik llegan a ti, {user}. Recíbelos con gratitud.",
    "{user}, your guardian's on leave but left an instruction.": "{user}, tu guardián está de vacaciones pero dejó una instrucción.",
    "The forces of nature whisper your name, {user}.": "Las fuerzas de la naturaleza susurran tu nombre, {user}.",
    "{user}, you have a rare aura. Guard it from envy.": "{user}, tienes un aura rara. Cuídala de la envidia.",
    "{user}, you're not late — you're right on time.": "{user}, no llegas tarde — llegas justo a tiempo.",
    "Today one deep conversation beats ten empty ones, {user}.": "Hoy una conversación profunda vale más que diez vacías, {user}.",
    "{user}, being yourself is the highest level-up.": "{user}, ser tú mismo es el mayor level-up.",
    "Today hug someone, {user}. Free magic.": "Hoy abraza a alguien, {user}. Magia gratis.",
    "Today do what you've been postponing, {user}. At least halfway.": "Hoy haz lo que has estado posponiendo, {user}. Al menos a medias.",
    "Today calling mom is wonderful, {user}. Truly.": "Hoy llamar a mamá es maravilloso, {user}. De verdad.",
    "{user}, iron a fresh shirt. Power!": "{user}, plancha una camisa limpia. ¡Poder!",
    "Today write down one thought, {user}. A year from now you'll appreciate it.": "Hoy anota un pensamiento, {user}. En un año lo agradecerás.",
    "{user}, take a mirror selfie with the pipirik. For memory.": "{user}, tómate una selfie con el pipirik. Para el recuerdo.",
    "Today's day for a tiny adventure, {user}. The tiniest.": "Hoy es día de una pequeña aventura, {user}. La más pequeña.",
    "The caravan awaits someone who fears nothing, {user}. That's you.": "La caravana espera a alguien que no le tema a nada, {user}. Ese eres tú.",
    "{user}, your pipirik is one of a kind. Treasure it.": "{user}, tu pipirik es único. Cuídalo.",
    "{user}, the dungeon isn't as scary as it seems. But the loot is real.": "{user}, la mazmorra no es tan aterradora como parece. Pero el botín es real.",
    "{user}, the mountains echo the names of winners. Yours is next.": "{user}, las montañas hacen eco de los nombres de los ganadores. El tuyo es el siguiente.",
    "Your pipirik grows while you sleep, {user}. Check in the morning.": "Tu pipirik crece mientras duermes, {user}. Revisa por la mañana.",
    "{user}, a pipirik-titan is awakening inside you.": "{user}, un pipirik-titán está despertando dentro de ti.",
    "The tribe will be proud of your contribution, {user}.": "La tribu estará orgullosa de tu contribución, {user}.",
    "Today's drop will make you say 'wow,' {user}.": "El drop de hoy te hará decir 'wow', {user}.",
    "{user}, there's a cave in the mountains with your name on it. Find it.": "{user}, hay una cueva en las montañas con tu nombre. Encuéntrala.",
    "The caravan carries something for you, {user}. Intercept it.": "La caravana lleva algo para ti, {user}. Intercéptala.",
    "{user}, the pipirik-scout returned with a report: all clear ahead.": "{user}, el pipirik-explorador volvió con un reporte: todo despejado adelante.",
    "{user}, mountains are where pipiriks become legends.": "{user}, las montañas son donde los pipiriks se vuelven leyendas.",
    "{user}, /predict — the champion's daily ritual.": "{user}, /predict — el ritual diario del campeón.",
    "{user}, the pipirik-veteran salutes you. At ease!": "{user}, el pipirik-veterano te saluda. ¡Descansa!",
    "Thickness defines stability, {user}. Stand firm.": "El grosor define la estabilidad, {user}. Mantente firme.",
    "{user}, a pipirik-legend begins with a single quest.": "{user}, una leyenda pipirik comienza con una sola misión.",
    "The caravan passes once in a lifetime, {user}. Or once a day.": "La caravana pasa una vez en la vida, {user}. O una vez al día.",
    "{user}, pipirik-champion — a title you've earned.": "{user}, pipirik-campeón — un título que te has ganado.",
    "Thickness at maximum, {user}. Time for battle.": "Grosor al máximo, {user}. Hora de la batalla.",
    "{user}, caravan loot is a credit to the whole tribe.": "{user}, el botín de la caravana es mérito de toda la tribu.",
    "{user}, the dungeon awaits a hero. The hero is you.": "{user}, la mazmorra espera un héroe. El héroe eres tú.",
    "{user}, the mountain peak is closer than it seems.": "{user}, la cima de la montaña está más cerca de lo que parece.",
    "{user}, you're not losing. You're learning to win.": "{user}, no estás perdiendo. Estás aprendiendo a ganar.",
    "Movement is life, {user}. Move.": "El movimiento es vida, {user}. Muévete.",
    "{user}, you're living proof that persistence works.": "{user}, eres la prueba viviente de que la persistencia funciona.",
    "Energy follows attention, {user}. Direct it well.": "La energía sigue a la atención, {user}. Dirígela bien.",
    "{user}, your potential outweighs your doubts.": "{user}, tu potencial supera tus dudas.",
    "{user}, action cures fear. Act.": "{user}, la acción cura el miedo. Actúa.",
    "Discipline bridges goals and results, {user}.": "La disciplina conecta metas y resultados, {user}.",
    "{user}, you're not what happened to you. You're what you chose.": "{user}, no eres lo que te pasó. Eres lo que elegiste.",
    "{user}, hardships make you antifragile. Welcome them.": "{user}, las dificultades te hacen antifrágil. Recíbelas.",
    "{user}, confidence is a habit. Start right now.": "{user}, la confianza es un hábito. Empieza ahora mismo.",
    "{user}, falling is normal. Staying down is not.": "{user}, caer es normal. Quedarse abajo no.",
    "Progress beats perfection, {user}.": "El progreso le gana a la perfección, {user}.",
    "{user}, you deserve what you're striving for.": "{user}, mereces lo que estás buscando.",
    "{user}, fear is a compass. Go where it's scary.": "{user}, el miedo es una brújula. Ve a donde da miedo.",
    "You're the driving force of change, {user}. Be it.": "Eres la fuerza motriz del cambio, {user}. Sé esa fuerza.",
    "Better to do and regret than not do and regret, {user}.": "Mejor hacer y arrepentirse que no hacer y arrepentirse, {user}.",
    "{user}, you're a rare specimen. Cherish yourself.": "{user}, eres un ejemplar raro. Valórate.",
    "Ambitions without action are fantasies, {user}. Act.": "Ambiciones sin acción son fantasías, {user}. Actúa.",
    "Today be the version of yourself you're proud of, {user}.": "Hoy sé la versión de ti mismo de la que estés orgulloso, {user}.",
    "You're a generator of possibilities, {user}. Switch on.": "Eres un generador de posibilidades, {user}. Enciéndete.",
    "{user}, you've got this. Not a wish — a forecast.": "{user}, tú puedes. No es un deseo — es un pronóstico.",
    "Keep moving, {user}. Even turtles finish the race.": "Sigue avanzando, {user}. Hasta las tortugas terminan la carrera.",
    "{user}, failure is not a period — it's a comma.": "{user}, el fracaso no es un punto — es una coma.",
    "{user}, one percent improvement daily equals 365% per year.": "{user}, un uno por ciento de mejora diaria equivale a 365% al año.",
    "{user}, the crystal in your pocket is charging.": "{user}, el cristal en tu bolsillo se está cargando.",
    "The pipirik amulet is charged to 100%, {user}.": "El amuleto pipirik está cargado al 100%, {user}.",
    "{user}, look in the mirror at exactly midnight. You'll see the future.": "{user}, mírate al espejo exactamente a medianoche. Verás el futuro.",
    "{user}, the shaman beats the drum approvingly. Hear it?": "{user}, el chamán toca el tambor con aprobación. ¿Lo oyes?",
    "The sands of time pour in your favor, {user}.": "Las arenas del tiempo caen a tu favor, {user}.",
    "{user}, an ancient prophecy begins to come true. For you.": "{user}, una antigua profecía empieza a cumplirse. Para ti.",
    "The pipirik-guardian protects you, {user}. Always.": "El pipirik-guardián te protege, {user}. Siempre.",
    "{user}, the crystal ball shows a smile for you.": "{user}, la bola de cristal muestra una sonrisa para ti.",
    "The ancient tree whispers: you're the chosen one, {user}.": "El árbol antiguo susurra: eres el elegido, {user}.",
    "{user}, esoteric advice: turn your ring thrice.": "{user}, consejo esotérico: gira tu anillo tres veces.",
    "{user}, a green aura means healing.": "{user}, un aura verde significa sanación.",
    "Tarot says: the Wheel of Fortune turned to you, {user}.": "El tarot dice: la Rueda de la Fortuna giró hacia ti, {user}.",
    "The Star card was drawn for you, {user}. Hope is strong.": "La carta de La Estrella salió para ti, {user}. La esperanza es fuerte.",
    "Luck ritual: blink three times and make a wish, {user}.": "Ritual de suerte: parpadea tres veces y pide un deseo, {user}.",
    "{user}, the pipirik constellation is at its peak. Act.": "{user}, la constelación pipirik está en su punto máximo. Actúa.",
    "The magic wand points at you, {user}.": "La varita mágica apunta hacia ti, {user}.",
    "{user}, an ancient artifact is activated. Do you feel it?": "{user}, un artefacto antiguo se ha activado. ¿Lo sientes?",
    "Luck spell: whisper your name three times, {user}.": "Hechizo de suerte: susurra tu nombre tres veces, {user}.",
    "{user}, the ritual is complete. Power is with you.": "{user}, el ritual está completo. El poder está contigo.",
    "{user}, the cosmos smiles at you. Smile back.": "{user}, el cosmos te sonríe. Devuélvele la sonrisa.",
    "Magic begins when you believe in it, {user}.": "La magia empieza cuando crees en ella, {user}.",
    "Magical protection is active, {user}. Fear nothing.": "La protección mágica está activa, {user}. No temas nada.",
    "{user}, cosmic vibrations are tuned to your frequency.": "{user}, las vibraciones cósmicas están sintonizadas a tu frecuencia.",
    "{user}, the magic circle is closing. You — in the center.": "{user}, el círculo mágico se está cerrando. Tú — en el centro.",
    "Night is the time of the strong, {user}. You're one of them.": "La noche es el momento de los fuertes, {user}. Tú eres uno de ellos.",
    "{user}, the magic mirror says: beauty is within.": "{user}, el espejo mágico dice: la belleza está adentro.",
    "{user}, the store line will melt like snow.": "{user}, la fila de la tienda se derretirá como nieve.",
    "{user}, an outlet will be right there. The one you need.": "{user}, habrá un enchufe justo ahí. El que necesitas.",
    "The microwave will heat exactly the right amount, {user}.": "El microondas calentará justo lo necesario, {user}.",
    "Today zero CAPTCHAs to solve, {user}.": "Hoy cero CAPTCHAs que resolver, {user}.",
    "Coffee will be the perfect temperature, {user}. Just how you like it.": "El café estará a la temperatura perfecta, {user}. Justo como te gusta.",
    "The ATM will dispense the exact bills you wanted, {user}.": "El cajero dará exactamente los billetes que querías, {user}.",
    "The phone charger will be found without a search, {user}.": "El cargador del teléfono aparecerá sin buscarlo, {user}.",
    "{user}, slippers will be right by the bed. Both of them.": "{user}, las pantuflas estarán junto a la cama. Las dos.",
    "{user}, no crumbs in bed. A clean-sheet day.": "{user}, sin migas en la cama. Un día de sábanas limpias.",
    "The towel will dry overnight, {user}. Drying magic.": "La toalla se secará durante la noche, {user}. Magia de secado.",
    "{user}, no line for the bathroom. Fantastic.": "{user}, sin fila para el baño. Fantástico.",
    "{user}, not a single mosquito. An itch-free day.": "{user}, ni un solo mosquito. Un día sin comezón.",
    "{user}, the kettle will boil faster than usual.": "{user}, la tetera hervirá más rápido de lo normal.",
    "{user}, nothing will stick to the pan.": "{user}, nada se pegará al sartén.",
    "Today zero robocalls, {user}.": "Hoy cero llamadas de spam, {user}.",
    "Today no car will splash you, {user}.": "Hoy ningún carro te salpicará, {user}.",
    "{user}, the coin will land on the side you called.": "{user}, la moneda caerá del lado que elegiste.",
    "Today puddles will avoid you, {user}.": "Hoy los charcos te evitarán, {user}.",
    "{user}, the swings in the park will be free.": "{user}, los columpios del parque estarán libres.",
    "{user}, the music in your headphones will be exactly right.": "{user}, la música en tus audífonos será perfecta.",
    "Not a single thread will snag, {user}. Clean look.": "Ni un solo hilo se enganchará, {user}. Look impecable.",
    "{user}, the iron will heat up in seconds.": "{user}, la plancha calentará en segundos.",
    "{user}, no nails will break. A strong-nails day.": "{user}, ninguna uña se romperá. Un día de uñas fuertes.",
    "Today zero app crashes, {user}. Almost.": "Hoy cero apps crasheando, {user}. Casi.",
    "{user}, there'll be a free seat on the bus.": "{user}, habrá un asiento libre en el camión.",
    "{user}, the envelope will tear neatly along the edge.": "{user}, el sobre se abrirá limpio por el borde.",
    "Today nothing will fall behind the nightstand, {user}.": "Hoy nada se caerá detrás del buró, {user}.",
    "The zip will close smoothly, {user}. Satisfaction!": "El cierre cerrará suavecito, {user}. ¡Satisfacción!",
    "{user}, not a single pop-up. Clean screen.": "{user}, ni un solo pop-up. Pantalla limpia.",
    "Today not a single pebble in your shoe, {user}.": "Hoy ni una piedrita en tu zapato, {user}.",
    "{user}, GPS will pick the right route.": "{user}, el GPS elegirá la ruta correcta.",
    "{user}, the clothing size online will match reality.": "{user}, la talla de ropa en línea coincidirá con la realidad.",
    "The apple will be juicy and crunchy, {user}.": "La manzana será jugosa y crujiente, {user}.",
    "{user}, the printout will be perfectly aligned.": "{user}, la impresión saldrá perfectamente alineada.",
    "{user}, curtains will slide without jamming. Light!": "{user}, las cortinas se deslizarán sin atorarse. ¡Luz!",
    "Today nothing will tumble out of the closet, {user}.": "Hoy nada se caerá del clóset, {user}.",
    "{user}, the tea will brew perfectly. No bitterness.": "{user}, el té quedará perfecto. Sin amargura.",
    "404: failure not found, {user}. Congratulations.": "404: fallo no encontrado, {user}. Felicidades.",
    "{user}, when life gives you lemons — open a lemonade stand.": "{user}, cuando la vida te dé limones — abre un puesto de limonada.",
    "{user}, the neural network confirms: you're awesome.": "{user}, la red neuronal confirma: eres genial.",
    "Your meme potential is off the charts, {user}.": "Tu potencial de memes está fuera de las gráficas, {user}.",
    "{user}, you've cleared the 'Monday' level. Respect.": "{user}, pasaste el nivel 'Lunes'. Respeto.",
    "You're top-1 in the pipirik rankings, {user}. In your imagination, at least.": "Eres top-1 en el ranking pipirik, {user}. En tu imaginación, al menos.",
    "{user}, pipirik-influencer — that's your future career.": "{user}, pipirik-influencer — esa es tu futura carrera.",
    "Luck installed. No reboot required, {user}.": "Suerte instalada. Sin reinicio necesario, {user}.",
    "You've hit 10,000 pipirik points, {user}. Achievement unlocked!": "¡Alcanzaste 10,000 puntos pipirik, {user}. Logro desbloqueado!",
    "{user}, pipirik upgrade available. Install?": "{user}, actualización pipirik disponible. ¿Instalar?",
    "Today retrograde Mercury went for tea, {user}.": "Hoy Mercurio retrógrado se fue a tomar té, {user}.",
    "The pipirik-metaverse awaits you, {user}.": "El pipirik-metaverso te espera, {user}.",
    "Today's RNG works for you, {user}. Statistically verified.": "El RNG de hoy trabaja para ti, {user}. Estadísticamente verificado.",
    "{user}, you've unlocked a hidden level: 'Good Day.'": "{user}, desbloqueaste un nivel oculto: 'Buen Día'.",
    "Pipirik-hacker cracked the sadness system, {user}. You're free!": "¡El pipirik-hacker hackeó el sistema de tristeza, {user}. Eres libre!",
    "You're a legendary drop from life's chest, {user}.": "Eres un drop legendario del cofre de la vida, {user}.",
    "Pipirik-bot is working for you 24/7, {user}.": "El pipirik-bot trabaja para ti 24/7, {user}.",
    "You're not a bug, you're a feature, {user}.": "No eres un bug, eres un feature, {user}.",
    "Hidden quest of the day: smile three times, {user}.": "Misión oculta del día: sonríe tres veces, {user}.",
    "Pipirik-android is indistinguishable from the real thing, {user}. You're the real deal!": "¡El pipirik-androide es indistinguible del real, {user}. Tú eres el original!",
    "You're a diamond in the ore of ordinary days, {user}.": "Eres un diamante en la mina de los días ordinarios, {user}.",
    "Today debug mode is on: all errors visible and fixable, {user}.": "Hoy el modo debug está activado: todos los errores visibles y reparables, {user}.",
    "Achievement unlocked: 'Survived Until Lunch,' {user}.": "Logro desbloqueado: 'Sobrevivió Hasta el Almuerzo', {user}.",
    "{user}, pipirik-disco: dance like nobody's watching.": "{user}, pipirik-disco: baila como si nadie te viera.",
    "God mode enabled, {user}. Act accordingly.": "Modo Dios activado, {user}. Actúa en consecuencia.",
    "Quest 'Good Day' accepted, {user}. Reward: contentment.": "Misión 'Buen Día' aceptada, {user}. Recompensa: satisfacción.",
    "{user}, loot box opened: epic pipirik inside!": "¡{user}, caja de botín abierta: pipirik épico adentro!",
    "Today's a clean commit: zero merge conflicts, {user}.": "Hoy es un commit limpio: cero merge conflicts, {user}.",
    "{user}, pipirik-dancer won the battle. For you!": "¡{user}, el pipirik-bailarín ganó la batalla. Por ti!",
    "Notification: 'Luck delivered,' {user}. Open it.": "Notificación: 'Suerte entregada', {user}. Ábrela.",
    "Luck progress bar: 99%… 100%! Done, {user}.": "Barra de progreso de suerte: 99%… ¡100%! Listo, {user}.",
    "{user}, pipirik-astronaut landed on the Moon. In your honor.": "{user}, el pipirik-astronauta aterrizó en la Luna. En tu honor.",
    "Pipirik-artist painted your portrait, {user}. Turned out beautiful.": "El pipirik-artista pintó tu retrato, {user}. Quedó hermoso.",
    "{user}, screenshot of the day: you on top.": "{user}, captura del día: tú en la cima.",
    "{user}, pipirik-analyst: trend is up.": "{user}, pipirik-analista: la tendencia va al alza.",
    "{user}, you're trending. Hashtag #PipirikOfTheDay.": "{user}, eres tendencia. Hashtag #PipirikDelDía.",
    "{user}, the 'like' button has been pressed. For you.": "{user}, el botón de 'like' fue presionado. Para ti.",
    "Luck Wi-Fi connected automatically, {user}.": "Wi-Fi de suerte conectado automáticamente, {user}.",
    "You're the Bitcoin of pipiriks, {user}. Appreciate.": "Eres el Bitcoin de los pipiriks, {user}. Aprécialo.",
    "Happiness is in the process, not the result, {user}.": "La felicidad está en el proceso, no en el resultado, {user}.",
    "{user}, water wears stone not by force, but by persistence.": "{user}, el agua desgasta la piedra no por fuerza, sino por persistencia.",
    "Simplicity is the ultimate sophistication, {user}.": "La simplicidad es la máxima sofisticación, {user}.",
    "The longest journey begins with a single step, {user}.": "El viaje más largo comienza con un solo paso, {user}.",
    "{user}, the world is a mirror. Smile — and it smiles back.": "{user}, el mundo es un espejo. Sonríe — y te sonreirá de vuelta.",
    "Patience is not weakness, {user}. It's strategy.": "La paciencia no es debilidad, {user}. Es estrategia.",
    "{user}, be grateful for what you have. The rest will follow.": "{user}, agradece lo que tienes. Lo demás vendrá.",
    "Words create reality, {user}. Choose them wisely.": "Las palabras crean la realidad, {user}. Elígelas sabiamente.",
    "{user}, those who know 'why' can endure any 'how.'": "{user}, quien sabe el 'por qué' puede soportar cualquier 'cómo'.",
    "Silence between notes makes the music, {user}.": "El silencio entre las notas hace la música, {user}.",
    "True freedom is responsibility for your choices, {user}.": "La verdadera libertad es la responsabilidad de tus elecciones, {user}.",
    "Better to be than to seem, {user}.": "Mejor ser que parecer, {user}.",
    "{user}, a journey of a thousand miles begins with one step.": "{user}, un viaje de mil millas comienza con un solo paso.",
    "{user}, time heals. But it also teaches.": "{user}, el tiempo sana. Pero también enseña.",
    "The ability to wait is a rare skill, {user}. Develop it.": "La capacidad de esperar es una habilidad rara, {user}. Desarróllala.",
    "{user}, the world belongs to those who are glad to be in it.": "{user}, el mundo pertenece a quienes se alegran de estar en él.",
    "Between stimulus and response is the space of choice, {user}.": "Entre el estímulo y la respuesta está el espacio de elección, {user}.",
    "{user}, not all who wander are lost.": "{user}, no todos los que deambulan están perdidos.",
    "{user}, learn from water: it's soft, yet it conquers stone.": "{user}, aprende del agua: es suave, pero conquista la piedra.",
    "{user}, a tree's roots are unseen, but without them — nothing.": "{user}, las raíces de un árbol no se ven, pero sin ellas — nada.",
    "Sometimes letting go means winning, {user}.": "A veces soltar significa ganar, {user}.",
    "{user}, the world is beautiful when seen through the right eyes.": "{user}, el mundo es hermoso cuando se ve con los ojos correctos.",
    "A drop of water is nothing, but the ocean is made of drops, {user}.": "Una gota de agua no es nada, pero el océano está hecho de gotas, {user}.",
    "{user}, a wise person makes bread from stone.": "{user}, una persona sabia hace pan de piedra.",
    "Today be your own anchor, {user}.": "Hoy sé tu propia ancla, {user}.",
    "{user}, not all bridges need burning. But some are necessary.": "{user}, no todos los puentes necesitan quemarse. Pero algunos es necesario.",
    "{user}, a true friend is one who values your pipirik.": "{user}, un verdadero amigo es quien valora tu pipirik.",
    "{user}, thank someone who helped you. It matters.": "{user}, agradécele a alguien que te ayudó. Importa.",
    "{user}, a team is stronger than a solo player. Unite!": "{user}, un equipo es más fuerte que un jugador solo. ¡Únete!",
    "Today be the friend you'd want to have, {user}.": "Hoy sé el amigo que te gustaría tener, {user}.",
    "{user}, tribal bonds are stronger than solo attacks.": "{user}, los lazos tribales son más fuertes que los ataques en solitario.",
    "True wealth is the people around you, {user}.": "La verdadera riqueza son las personas a tu alrededor, {user}.",
    "Today someone among your friends needs support, {user}. Be there.": "Hoy alguien entre tus amigos necesita apoyo, {user}. Está ahí.",
    "Today say 'thank you' to the person who cooks for you, {user}.": "Hoy dile 'gracias' a la persona que cocina para ti, {user}.",
    "Today host a tea party with a friend, {user}. Even online.": "Hoy organiza una fiesta de té con un amigo, {user}. Aunque sea en línea.",
    "Today text someone you miss, {user}.": "Hoy mándale mensaje a alguien que extrañas, {user}.",
    "Today invite someone for dinner, {user}.": "Hoy invita a alguien a cenar, {user}.",
    "Helping another is helping yourself, {user}.": "Ayudar a otro es ayudarte a ti mismo, {user}.",
    "Start a poll: where to go together, {user}.": "Inicia una encuesta: a dónde ir juntos, {user}.",
    "Today offer help without waiting to be asked, {user}.": "Hoy ofrece ayuda sin esperar a que te la pidan, {user}.",
    "{user}, one warm look is worth a thousand words.": "{user}, una mirada cálida vale más que mil palabras.",
    "Today smile at a stranger, {user}. It's cool.": "Hoy sonríele a un desconocido, {user}. Es genial.",
    "{user}, text 'how are you?' — and hear a story.": "{user}, manda un '¿cómo estás?' — y escucha una historia.",
    "Tip of the day: be generous with words of support, {user}.": "Tip del día: sé generoso con palabras de apoyo, {user}.",
    "{user}, with the tribe, you're invincible.": "{user}, con la tribu, eres invencible.",
    "Today hug a pipirik, {user}. Yours, of course.": "Hoy abraza un pipirik, {user}. El tuyo, claro.",
    "Like for support, {user}. You've got it!": "Like de apoyo, {user}. ¡Lo tienes!",
    "Today do something nice for a stranger, {user}.": "Hoy haz algo bueno por un desconocido, {user}.",
    "{user}, true warriors have each other's backs.": "{user}, los verdaderos guerreros se cuidan las espaldas.",
    "Send a 'well done' to someone who's trying, {user}.": "Manda un 'bien hecho' a alguien que se esfuerza, {user}.",
    "{user}, the tribal chat is for support, not arguments.": "{user}, el chat de la tribu es para apoyarse, no para discutir.",
    "Today praise someone, {user}. Sincerely.": "Hoy elogia a alguien, {user}. De corazón.",
    "{user}, together you can move mountains. And dungeons.": "{user}, juntos pueden mover montañas. Y mazmorras.",
    "{user}, the toast will land butter-side up. Guaranteed.": "{user}, la tostada caerá con la mantequilla para arriba. Garantizado.",
    "{user}, the watermelon will be sweet. Try it.": "{user}, la sandía estará dulce. Pruébala.",
    "{user}, a second coffee isn't a sin. It's strategy.": "{user}, un segundo café no es pecado. Es estrategia.",
    "{user}, chocolate is pipirik fuel. Refuel.": "{user}, el chocolate es combustible pipirik. Recarga.",
    "{user}, banana — the most meme-worthy fruit. Eat with dignity.": "{user}, plátano — la fruta más memeable. Come con dignidad.",
    "Evening tea — a ritual of wise pipiriks, {user}.": "Té de la tarde — un ritual de pipiriks sabios, {user}.",
    "{user}, mango — the fruit of kings. You're worthy.": "{user}, mango — la fruta de los reyes. Eres digno.",
    "{user}, bread from the oven beats any dessert.": "{user}, pan recién salido del horno le gana a cualquier postre.",
    "{user}, kefir before bed — pipirik-dietician's advice.": "{user}, kéfir antes de dormir — consejo del pipirik-nutriólogo.",
    "{user}, lemonade — the drink of champions. Sip!": "{user}, limonada — la bebida de los campeones. ¡Dale un trago!",
    "{user}, compote — the drink of ancestors. Respect the tradition.": "{user}, compota — la bebida de los ancestros. Respeta la tradición.",
    "{user}, pancakes — Sunday morning currency.": "{user}, hot cakes — la moneda de los domingos por la mañana.",
    "{user}, the steak will be grilled to exactly the right doneness.": "{user}, el bistec quedará asado en su punto exacto.",
    "A bagel — the perfect shape, {user}. Like your journey.": "Una dona — la forma perfecta, {user}. Como tu camino.",
    "{user}, strawberries will be sweet without sugar.": "{user}, las fresas estarán dulces sin azúcar.",
    "The crepe will roll without cracking, {user}. Mastery!": "¡La crepa se enrollará sin romperse, {user}. Maestría!",
    "{user}, mint water — the elixir of pep.": "{user}, agua de menta — el elixir de la energía.",
    "Pumpkin soup — a warm hug in a bowl, {user}.": "Sopa de calabaza — un abrazo cálido en un plato, {user}.",
    "{user}, dark bread is the pipirik-diet staple.": "{user}, pan negro es la base de la dieta pipirik.",
    "{user}, yogurt — the intellectual's breakfast.": "{user}, yogur — el desayuno de los intelectuales.",
    "{user}, a waffle with tea — the classic of comfort.": "{user}, un waffle con té — el clásico del confort.",
    "{user}, buckwheat is a superfood. Sorry if you disagree.": "{user}, el trigo sarraceno es un superalimento. Perdón si no estás de acuerdo.",
    "Today peanut butter is your ally, {user}.": "Hoy la mantequilla de maní es tu aliada, {user}.",
    "{user}, eat fruits — they charge the pipirik.": "{user}, come frutas — cargan al pipirik.",
    "{user}, undercooked rice is unfinished work. Cook it through!": "¡{user}, el arroz crudo es trabajo sin terminar. Cocínalo bien!",
    "{user}, fruit jelly is a mysterious drink. Give it a try.": "{user}, la gelatina de frutas es una bebida misteriosa. Dale una probada.",
    "{user}, dates — sweetness without guilt.": "{user}, dátiles — dulzura sin culpa.",
    "{user}, jam on bread — an eternal classic.": "{user}, mermelada en pan — un clásico eterno.",
    "Today walk for at least 15 minutes, {user}. Your body will thank you.": "Hoy camina al menos 15 minutos, {user}. Tu cuerpo te lo agradecerá.",
    "{user}, stretching is an underrated skill. Stretch.": "{user}, estirarse es una habilidad subestimada. Estírate.",
    "{user}, breathe deeply. Three breaths in, three out. Better?": "{user}, respira profundo. Tres respiraciones adentro, tres afuera. ¿Mejor?",
    "{user}, drink water. Seriously. Drink.": "{user}, toma agua. En serio. Toma.",
    "Today slow down, {user}. The world can wait.": "Hoy ve más despacio, {user}. El mundo puede esperar.",
    "{user}, a smile in the mirror is free therapy.": "{user}, una sonrisa al espejo es terapia gratis.",
    "{user}, a hot bath is a cure for all ills.": "{user}, un baño caliente es cura para todos los males.",
    "{user}, music heals. Play your favorite.": "{user}, la música sana. Pon tu favorita.",
    "Today go to bed an hour early, {user}. Revolution!": "¡Hoy acuéstate una hora antes, {user}. Revolución!",
    "{user}, a contrast shower is a hero's awakening.": "{user}, una ducha de contraste es el despertar de un héroe.",
    "Today draw something, {user}. Doesn't matter how — what matters is that you do.": "Hoy dibuja algo, {user}. No importa cómo — lo que importa es que lo hagas.",
    "{user}, turn off notifications. At least for half an hour.": "{user}, apaga las notificaciones. Al menos por media hora.",
    "{user}, walk after lunch. Your digestion will thank you.": "{user}, camina después de comer. Tu digestión te lo agradecerá.",
    "Today sit in silence for 5 minutes, {user}. It's a reboot.": "Hoy siéntate en silencio 5 minutos, {user}. Es un reinicio.",
    "Morning exercise is a habit of kings, {user}.": "El ejercicio matutino es un hábito de reyes, {user}.",
    "Today be kinder to yourself, {user}. You're worth it.": "Hoy sé más amable contigo mismo, {user}. Lo vales.",
    "{user}, forgive yourself for mistakes. They're part of the journey.": "{user}, perdónate por los errores. Son parte del camino.",
    "Today find 10 minutes for meditation, {user}.": "Hoy encuentra 10 minutos para meditar, {user}.",
    "{user}, read a paper book. Screens can wait.": "{user}, lee un libro de papel. Las pantallas pueden esperar.",
    "Today do 20 squats, {user}. Pipirik-fitness!": "¡Hoy haz 20 sentadillas, {user}. Pipirik-fitness!",
    "Today say 'no' to extra obligations, {user}.": "Hoy di 'no' a las obligaciones extra, {user}.",
    "Try sleeping without a pillow, {user}. Your neck will thank you.": "Intenta dormir sin almohada, {user}. Tu cuello te lo agradecerá.",
    "{user}, yawn without shame. It's nature.": "{user}, bosteza sin vergüenza. Es natural.",
    "{user}, aromatherapy: lavender for relaxation.": "{user}, aromaterapia: lavanda para relajarte.",
    "Walk 10,000 steps, {user}. Or at least 5,000.": "Camina 10,000 pasos, {user}. O al menos 5,000.",
    "Today drink a glass of water on an empty stomach, {user}.": "Hoy toma un vaso de agua en ayunas, {user}.",
    "{user}, breathe from your belly. It calms you instantly.": "{user}, respira desde el vientre. Te calma al instante.",
    "Spend time in nature, {user}. At least in a park.": "Pasa tiempo en la naturaleza, {user}. Al menos en un parque.",
    "{user}, hug a pillow. That counts too.": "{user}, abraza una almohada. Eso también cuenta.",
    "Learn to say 'no' without guilt, {user}.": "Aprende a decir 'no' sin culpa, {user}.",
    "{user}, pipirik tip: go to bed before midnight.": "{user}, tip pipirik: acuéstate antes de medianoche.",
    "Today throw out something unnecessary, {user}. Lightness!": "¡Hoy tira algo innecesario, {user}. Ligereza!",
    "{user}, take the stairs instead of the elevator.": "{user}, toma las escaleras en vez del elevador.",
    "{user}, hug yourself. You're awesome.": "{user}, abrázate. Eres genial.",
    "You deserve all the hugs in the world, {user}.": "Mereces todos los abrazos del mundo, {user}.",
    "{user}, someone is thinking about you warmly right now.": "{user}, alguien está pensando en ti con cariño en este momento.",
    "{user}, you're a quiet hero in someone's life.": "{user}, eres un héroe silencioso en la vida de alguien.",
    "{user}, you make the world safer simply by existing.": "{user}, haces el mundo más seguro solo con existir.",
    "The world rests on people like you, {user}. Thank you.": "El mundo se sostiene en personas como tú, {user}. Gracias.",
    "You're an invisible angel for many, {user}.": "Eres un ángel invisible para muchos, {user}.",
    "{user}, you're the person someone can call at 3 AM.": "{user}, eres la persona a la que alguien puede llamar a las 3 AM.",
    "{user}, your presence makes the room warmer.": "{user}, tu presencia hace la habitación más cálida.",
    "The world would be emptier without you, {user}.": "El mundo estaría más vacío sin ti, {user}.",
    "{user}, you're the hand that reaches out when needed.": "{user}, eres la mano que se extiende cuando se necesita.",
    "You're a quiet melody in a noisy world, {user}.": "Eres una melodía tranquila en un mundo ruidoso, {user}.",
    "You're the one people seek for support, {user}.": "Eres a quien la gente busca para apoyo, {user}.",
    "Today someone will be proud to know you, {user}.": "Hoy alguien estará orgulloso de conocerte, {user}.",
    "{user}, flowers bloom from your laughter.": "{user}, las flores florecen con tu risa.",
    "{user}, the world hugs you back.": "{user}, el mundo te abraza de vuelta.",
    "You're the reason someone believes in people, {user}.": "Eres la razón por la que alguien cree en la gente, {user}.",
    "You make an ordinary day special, {user}.": "Haces que un día ordinario sea especial, {user}.",
    "{user}, you're a rare flower in the garden of life.": "{user}, eres una flor rara en el jardín de la vida.",
    "You hear what's left unsaid, {user}.": "Escuchas lo que no se dice, {user}.",
    "You're the one who offers a hand without asking, {user}.": "Eres quien ofrece la mano sin que se lo pidan, {user}.",
    "{user}, the world spins a little easier thanks to you.": "{user}, el mundo gira un poco más fácil gracias a ti.",
    "{user}, your voice is a balm for the weary.": "{user}, tu voz es un bálsamo para los cansados.",
    "{user}, you're a gentle giant among ordinary people.": "{user}, eres un gigante gentil entre la gente común.",
    "You're the one who makes Monday bearable, {user}.": "Eres quien hace el lunes soportable, {user}.",
    "{user}, your warmth is felt through the screen.": "{user}, tu calidez se siente a través de la pantalla.",
    "You're a living motivator, {user}. And free of charge.": "Eres un motivador viviente, {user}. Y gratis.",
    "You're a walking comfort zone, {user}.": "Eres una zona de confort caminante, {user}.",
    "{user}, you're warm coffee on a Monday morning.": "{user}, eres café caliente un lunes por la mañana.",
    "Today someone will copy your smile, {user}.": "Hoy alguien copiará tu sonrisa, {user}.",
    "{user}, you're a drop of honey in someone's bitter day.": "{user}, eres una gota de miel en el día amargo de alguien.",
    "{user}, your sincerity is disarming.": "{user}, tu sinceridad es desarmante.",
    "{user}, you're the one kids and cats are drawn to.": "{user}, eres a quien los niños y los gatos se acercan.",
    "You're a roof over someone's head, {user}. Metaphorically.": "Eres un techo sobre la cabeza de alguien, {user}. Metafóricamente.",
    "{user}, the world is a little kinder when you're online.": "{user}, el mundo es un poco más amable cuando estás en línea.",
    "You're the warmest person in this chat, {user}.": "Eres la persona más cálida de este chat, {user}.",
    "You're living proof the world isn't lost, {user}.": "Eres la prueba viviente de que el mundo no está perdido, {user}.",
    "{user}, you're the one remembered in prayers.": "{user}, eres a quien recuerdan en las oraciones.",
    "You're a wizard who turns sadness into smiles, {user}.": "Eres un mago que convierte la tristeza en sonrisas, {user}.",
    "You're the story worth telling grandchildren, {user}.": "Eres la historia que vale la pena contarle a los nietos, {user}.",
    "You're proof that angels walk among us, {user}.": "Eres la prueba de que los ángeles caminan entre nosotros, {user}.",
    "{user}, the world feels safe around you.": "{user}, el mundo se siente seguro a tu alrededor.",
    "{user}, you're like home comfort, but in human form.": "{user}, eres como la comodidad del hogar, pero en forma humana.",
    "You're the one who makes people believe in miracles, {user}.": "Eres quien hace que la gente crea en milagros, {user}.",
    "You're a melody worth replaying, {user}.": "Eres una melodía que vale la pena repetir, {user}.",
    "{user}, you're warm sand underfoot.": "{user}, eres arena cálida bajo los pies.",
    "{user}, you're nature's smile.": "{user}, eres la sonrisa de la naturaleza.",
    "You're living spring, {user}. Always.": "Eres primavera viviente, {user}. Siempre.",
    "{user}, you're life's finest compliment.": "{user}, eres el mejor cumplido de la vida.",
    "{user}, you're tenderness in a rough world.": "{user}, eres ternura en un mundo rudo.",
    "You're morning dew on petals, {user}.": "Eres rocío de la mañana en los pétalos, {user}.",
    "{user}, you're protection from loneliness.": "{user}, eres protección contra la soledad.",
    "{user}, you're a favorite song on repeat.": "{user}, eres una canción favorita en repetición.",
    "You're a place people want to return to, {user}.": "Eres un lugar al que la gente quiere volver, {user}.",
    "{user}, you're a promise that comes true.": "{user}, eres una promesa que se cumple.",
    "You're the smell of fresh bread in the morning, {user}.": "Eres el olor a pan recién horneado por la mañana, {user}.",
    "{user}, you're a cozy blanket and hot cocoa.": "{user}, eres una cobija acogedora y chocolate caliente.",
    "{user}, you're the taste of mom's soup.": "{user}, eres el sabor de la sopa de mamá.",
    "{user}, you're the sound of a lullaby.": "{user}, eres el sonido de una canción de cuna.",
    "{user}, you're an invisible shield for the weak.": "{user}, eres un escudo invisible para los débiles.",
    "{user}, you're a breath of fresh air.": "{user}, eres un soplo de aire fresco.",
    "{user}, you're the one worth waking up for.": "{user}, eres por quien vale la pena despertar.",
    "The oracle sees your future, {user}. There's a couch and a phone.": "El oráculo ve tu futuro, {user}. Hay un sofá y un teléfono.",
    "{user}, prediction: you'll read this, smile, and change nothing.": "{user}, predicción: leerás esto, sonreirás y no cambiarás nada.",
    "{user}, the oracle is tired of you. But work is work.": "{user}, el oráculo está cansado de ti. Pero el trabajo es trabajo.",
    "Luck smiles at you, {user}. But it's a nervous tic.": "La suerte te sonríe, {user}. Pero es un tic nervioso.",
    "The oracle sees you're full of determination, {user}. Until lunch.": "El oráculo ve que estás lleno de determinación, {user}. Hasta la comida.",
    "The oracle believes in you, {user}. Nobody else does, but the oracle — yes.": "El oráculo cree en ti, {user}. Nadie más, pero el oráculo — sí.",
    "{user}, prediction: you'll spend the day efficiently. On YouTube.": "{user}, predicción: pasarás el día eficientemente. En YouTube.",
    "Oracle whispers: {user}, you're magnificent. Well, the oracle tries to be polite.": "El oráculo susurra: {user}, eres magnífico. Bueno, el oráculo intenta ser amable.",
    "{user}, prediction: you'll go to bed later than planned. Again.": "{user}, predicción: te acostarás más tarde de lo planeado. De nuevo.",
    "{user}, you're a diamond. Uncut. Very uncut.": "{user}, eres un diamante. Sin pulir. Muy sin pulir.",
    "Stars say: {user} promises to jog in the mornings. Again.": "Las estrellas dicen: {user} promete trotar por las mañanas. De nuevo.",
    "{user}, you're like subway Wi-Fi — technically there, but barely useful.": "{user}, eres como el Wi-Fi del metro — técnicamente ahí, pero apenas sirve.",
    "Stars say: you have a rare talent, {user}. Procrastinating.": "Las estrellas dicen: tienes un talento raro, {user}. Procrastinar.",
    "{user}, you're unique. Just like the other 8 billion.": "{user}, eres único. Igual que los otros 8 mil millones.",
    "The oracle believes you'll change the world, {user}. Start with the socks.": "El oráculo cree que cambiarás el mundo, {user}. Empieza por los calcetines.",
    "Prediction: {user} will set an alarm and ignore it.": "Predicción: {user} pondrá una alarma y la ignorará.",
    "{user}, the oracle admires your ability to do nothing productively.": "{user}, el oráculo admira tu habilidad de no hacer nada productivamente.",
    "{user}, the oracle sees potential in you. Deep. Very deep.": "{user}, el oráculo ve potencial en ti. Profundo. Muy profundo.",
    "Stars whisper: {user}, you're irreplaceable. Like a Wi-Fi router.": "Las estrellas susurran: {user}, eres irremplazable. Como un router de Wi-Fi.",
    "Luck awaits you, {user}. Wait, it left. It'll come back.": "La suerte te espera, {user}. Espera, se fue. Ya regresa.",
    "{user}, you're like a Windows update — slow, unpredictable, nobody asked.": "{user}, eres como una actualización de Windows — lento, impredecible, nadie la pidió.",
    "Oracle whispers: {user}, you're a procrastination master.": "El oráculo susurra: {user}, eres un maestro de la procrastinación.",
    "The oracle sees: {user} will set 10 alarms and ignore them all.": "El oráculo ve: {user} pondrá 10 alarmas y las ignorará todas.",
    "{user}, prediction: you'll open social media 'for a second.' Spoiler: no.": "{user}, predicción: abrirás las redes 'un segundo'. Spoiler: no.",
    "Luck glances at you, {user}. And walks away faster.": "La suerte te mira, {user}. Y se aleja más rápido.",
    "The oracle sees: {user}, you're heading to the goal. The long way. Very long.": "El oráculo ve: {user}, vas hacia la meta. Por el camino largo. Muy largo.",
    "Stars say: {user}, you're an encyclopedia of excuses.": "Las estrellas dicen: {user}, eres una enciclopedia de excusas.",
    "{user}, you're like decaf coffee — technically exists, but what's the point?": "{user}, eres como café descafeinado — técnicamente existe, pero ¿cuál es el punto?",
    "Oracle whispers: {user}, you're quite the character.": "El oráculo susurra: {user}, eres todo un personaje.",
    "Stars whisper: {user}, you're a riddle nobody wants to solve.": "Las estrellas susurran: {user}, eres un enigma que nadie quiere resolver.",
    "Stars say: {user}, your comfort zone is an entire continent.": "Las estrellas dicen: {user}, tu zona de confort es un continente entero.",
    "Oracle whispers: {user}, you're magnificent. In your fantasies.": "El oráculo susurra: {user}, eres magnífico. En tus fantasías.",
    "The oracle sees: {user}, you're growing. Sideways.": "El oráculo ve: {user}, estás creciendo. De lado.",
    "Prediction: {user} will say 'I'm ready for change' and order the usual.": "Predicción: {user} dirá 'estoy listo para el cambio' y pedirá lo de siempre.",
    "Oracle whispers: {user}, you're a masterpiece of incompleteness.": "El oráculo susurra: {user}, eres una obra maestra de lo incompleto.",
    "Prediction: {user} will set a goal. Then move it. Then forget it.": "Predicción: {user} pondrá una meta. Luego la moverá. Luego la olvidará.",
    "{user}, you're a planning master. Not execution — planning.": "{user}, eres un maestro de la planeación. No de la ejecución — de la planeación.",
    "Stars say: {user}, you're a life expert. Theorist.": "Las estrellas dicen: {user}, eres un experto en la vida. Teórico.",
    "Prediction: {user} will wake up early. To the neighbor's alarm.": "Predicción: {user} se despertará temprano. Por la alarma del vecino.",
    "{user}, you're like GPS without internet — has direction, no use.": "{user}, eres como GPS sin internet — tiene dirección, pero no sirve.",
    "Oracle whispers: {user}, you're a diamond. In a pile of coal.": "El oráculo susurra: {user}, eres un diamante. En un montón de carbón.",
    "Stars whisper: {user}, you're an inspiration. For memes.": "Las estrellas susurran: {user}, eres una inspiración. Para memes.",
    "{user}, you're like April weather — unpredictable, mostly cloudy.": "{user}, eres como el clima de abril — impredecible, mayormente nublado.",
    "Oracle whispers: {user}, you're a diamond. Without cut, polish, or carats.": "El oráculo susurra: {user}, eres un diamante. Sin corte, sin pulido, ni quilates.",
    "Stars whisper: {user}, you're a jack of all trades. Master of none, but sounds nice.": "Las estrellas susurran: {user}, eres todólogo. Maestro de nada, pero suena bonito.",
    "Prediction: {user} will say 'I need to think about it' instead of 'no.' As usual.": "Predicción: {user} dirá 'necesito pensarlo' en vez de 'no'. Como siempre.",
    "{user}, you're like a tea bag — shows your true colors in hot water.": "{user}, eres como una bolsita de té — muestras tus verdaderos colores en agua caliente.",
    "Stars whisper: {user}, you're a legend. In your imagination.": "Las estrellas susurran: {user}, eres una leyenda. En tu imaginación.",
    "Prediction: {user} will exercise. Their phone.": "Predicción: {user} hará ejercicio. Con su teléfono.",
    "Stars say: {user}, you're a living oxymoron. Ambitious slacker.": "Las estrellas dicen: {user}, eres un oxímoron viviente. Flojo ambicioso.",
    "Stars whisper: {user}, you're an artifact of an era. Which one — unspecified.": "Las estrellas susurran: {user}, eres un artefacto de una era. Cuál — no se especifica.",
    "{user}, you're like a sale — looks attractive, but fine print applies.": "{user}, eres como una oferta — se ve atractiva, pero aplican restricciones.",
    "The oracle sees: {user}, you're an idea generator. Not an executor — a generator.": "El oráculo ve: {user}, eres un generador de ideas. No un ejecutor — un generador.",
    "{user}, you're like antivirus — supposedly protects, but slows the system down.": "{user}, eres como un antivirus — supuestamente protege, pero hace el sistema lento.",
    "Stars whisper: {user}, you're a find. For an archaeologist.": "Las estrellas susurran: {user}, eres un hallazgo. Para un arqueólogo.",
    "Prediction: {user} will turn off the phone and live in the moment. Five seconds later, turns it back on.": "Predicción: {user} apagará el teléfono y vivirá el momento. Cinco segundos después, lo prende de nuevo.",
    "The oracle sees: {user}, you're the standard of consistency. Consistent laziness.": "El oráculo ve: {user}, eres el estándar de la consistencia. Consistente flojera.",
    "Stars say: {user}, you're a party person. When you're asleep.": "Las estrellas dicen: {user}, eres un fiestero. Cuando duermes.",
    "Prediction: {user} will say 'this is my final form' and lie on the couch.": "Predicción: {user} dirá 'esta es mi forma final' y se acostará en el sofá.",
    "{user}, you're like April weather — unpredictable, but mostly cloudy.": "{user}, eres como el clima de abril — impredecible, pero mayormente nublado.",
    "{user}, the dungeon has set a trap. Just for you.": "{user}, la mazmorra preparó una trampa. Solo para ti.",
    "Today disappointment awaits, {user}. And another one.": "Hoy te espera una decepción, {user}. Y otra más.",
    "Luck unsubscribed you, {user}.": "La suerte se desinscribió de ti, {user}.",
    "Stars whisper: {user}, you're a target. For trouble.": "Las estrellas susurran: {user}, eres un blanco. Para los problemas.",
    "The oracle sees: {user}, you'll lose something important. Small, but important.": "El oráculo ve: {user}, perderás algo importante. Pequeño, pero importante.",
    "{user}, the mountains mock you. The echo will confirm.": "{user}, las montañas se burlan de ti. El eco lo confirmará.",
    "{user}, the dungeon boss awaits you specifically. With extra zeal.": "{user}, el jefe de la mazmorra te espera específicamente. Con ganas extra.",
    "Luck took the day off, {user}. The whole day.": "La suerte se tomó el día libre, {user}. Todo el día.",
    "{user}, the pipirik refuses to grow. Mutiny.": "{user}, el pipirik se niega a crecer. Motín.",
    "{user}, you'll lose the caravan battle. The oracle is certain.": "{user}, perderás la batalla de la caravana. El oráculo está seguro.",
    "Stars whisper: {user}, someone is plotting against you.": "Las estrellas susurran: {user}, alguien está conspirando en tu contra.",
    "{user}, the mountains will send a rockslide. In your honor.": "{user}, las montañas enviarán una avalancha de rocas. En tu honor.",
    "Luck updated its blacklist, {user}. You're on it.": "La suerte actualizó su lista negra, {user}. Estás en ella.",
    "{user}, the pipirik-sage advises: hide.": "{user}, el pipirik-sabio aconseja: escóndete.",
    "{user}, the tribe is talking behind your back.": "{user}, la tribu habla a tus espaldas.",
    "The oracle sees: {user}, you'll step on something wet. Barefoot.": "El oráculo ve: {user}, pisarás algo mojado. Descalzo.",
    "{user}, the dungeon will collapse. Right after you enter.": "{user}, la mazmorra se derrumbará. Justo después de que entres.",
    "{user}, the mountains will fill with fog. Just for you.": "{user}, las montañas se llenarán de niebla. Solo para ti.",
    "Today RNG is against you, {user}. All of it.": "Hoy el RNG está en tu contra, {user}. Todo.",
    "{user}, the caravan will turn around upon seeing you.": "{user}, la caravana dará la vuelta al verte.",
    "The oracle sees: {user}, you'll trip. On flat ground.": "El oráculo ve: {user}, te tropezarás. En terreno plano.",
    "Luck wrote a will, {user}. Left you nothing.": "La suerte escribió un testamento, {user}. No te dejó nada.",
    "{user}, tribal bonus — 0. Coincidence? No.": "{user}, bono tribal — 0. ¿Coincidencia? No.",
    "{user}, the pipirik went on strike. Demands undisclosed.": "{user}, el pipirik se fue a huelga. Demandas no reveladas.",
    "Oracle whispers: {user}, you'll mix up salt and sugar. Again.": "El oráculo susurra: {user}, confundirás la sal con el azúcar. De nuevo.",
    "{user}, the mountains laugh. At you.": "{user}, las montañas se ríen. De ti.",
    "Luck changed its number, {user}. No notice.": "La suerte cambió de número, {user}. Sin aviso.",
    "{user}, the caravan is overloaded. No room for you.": "{user}, la caravana está sobrecargada. No hay lugar para ti.",
    "{user}, the dungeon flooded. Right after you entered.": "{user}, la mazmorra se inundó. Justo después de que entraste.",
    "{user}, the tribe sent you on reconnaissance. No return trip.": "{user}, la tribu te mandó de reconocimiento. Sin boleto de regreso.",
    "Stars whisper: {user}, phone battery will die at 1%.": "Las estrellas susurran: {user}, la batería del teléfono morirá al 1%.",
    "The pipirik sees: {user}, you'll do the exact opposite of what's needed.": "El pipirik ve: {user}, harás exactamente lo contrario de lo necesario.",
    "Luck went on vacation, {user}. Didn't buy a return ticket.": "La suerte se fue de vacaciones, {user}. No compró boleto de regreso.",
    "{user}, caravan loot — rocks. Only rocks.": "{user}, botín de la caravana — piedras. Solo piedras.",
    "The oracle sees: {user}, the elevator will break on your floor.": "El oráculo ve: {user}, el elevador se descompondrá en tu piso.",
    "Stars whisper: {user}, you'll sleep through something important.": "Las estrellas susurran: {user}, te quedarás dormido en algo importante.",
    "{user}, the mountains sent an avalanche. Not in your honor — at you.": "{user}, las montañas enviaron una avalancha. No en tu honor — hacia ti.",
    "{user}, the dungeon prepared negative drops.": "{user}, la mazmorra preparó drops negativos.",
    "The pipirik sees: {user}, Wi-Fi will cut out mid-call.": "El pipirik ve: {user}, el Wi-Fi se cortará a mitad de llamada.",
    "{user}, the mountains sent you a bill. For the air.": "{user}, las montañas te mandaron una factura. Por el aire.",
    "Luck changed the password, {user}. Hint — it's not your name.": "La suerte cambió la contraseña, {user}. Pista — no es tu nombre.",
    "{user}, the tribe voted. You lost.": "{user}, la tribu votó. Perdiste.",
    "The oracle sees: {user}, you'll drop your phone. Screen down.": "El oráculo ve: {user}, se te caerá el teléfono. Con la pantalla abajo.",
    "{user}, the mountains built you a maze. No exit.": "{user}, las montañas te construyeron un laberinto. Sin salida.",
    "Oracle whispers: {user}, someone ate your lunch. Already.": "El oráculo susurra: {user}, alguien se comió tu almuerzo. Ya.",
    "{user}, the caravan turned back. Because of you.": "{user}, la caravana se devolvió. Por tu culpa.",
    "The pipirik sees: {user}, you'll spill coffee. On white.": "El pipirik ve: {user}, derramarás café. Sobre blanco.",
    "{user}, the tribal council rejected your application.": "{user}, el consejo tribal rechazó tu solicitud.",
    "The oracle sees: {user}, you'll pick the slowest checkout line.": "El oráculo ve: {user}, elegirás la fila más lenta de la caja.",
    "Today nothing will work, {user}. Nothing at all.": "Hoy nada funcionará, {user}. Nada de nada.",
    "{user}, the mountains sent a rejection. No explanation.": "{user}, las montañas mandaron un rechazo. Sin explicación.",
    "Luck prepared a speech, {user}. A farewell one.": "La suerte preparó un discurso, {user}. Uno de despedida.",
    "{user}, the dungeon promises: enter and you'll regret it.": "{user}, la mazmorra promete: entra y te arrepentirás.",
    "Stars say: {user}, internet will be slow. All day.": "Las estrellas dicen: {user}, el internet estará lento. Todo el día.",
    "{user}, the tribe sent you into exile. With a smile.": "{user}, la tribu te mandó al exilio. Con una sonrisa.",
    "{user}, the caravan canceled. Technical reasons. Named {user}.": "{user}, la caravana se canceló. Razones técnicas. Llamadas {user}.",
    "The pipirik sees: {user}, you'll sit on gum.": "El pipirik ve: {user}, te sentarás en un chicle.",
    "{user}, the dungeon is overloaded. Closed for you.": "{user}, la mazmorra está sobrecargada. Cerrada para ti.",
    "{user}, the tribe considers you a burden. Silently.": "{user}, la tribu te considera una carga. En silencio.",
    "Stars say: {user}, you're a cosmic error. But an amusing one.": "Las estrellas dicen: {user}, eres un error cósmico. Pero divertido.",
    "{user}, the mountains sent an avalanche. Addressed to {user}.": "{user}, las montañas mandaron una avalancha. A nombre de {user}.",
    "{user}, caravan loot — minus 10 cm. Oops.": "{user}, botín de la caravana — menos 10 cm. Ups.",
    "The oracle sees: {user}, you'll step on LEGO. Three times.": "El oráculo ve: {user}, pisarás un LEGO. Tres veces.",
    "Stars say: {user}, you're a chaos generator. Involuntarily.": "Las estrellas dicen: {user}, eres un generador de caos. Involuntariamente.",
    "{user}, the caravan detoured around you. By 200 km.": "{user}, la caravana hizo un desvío para evitarte. De 200 km.",
    "{user}, the dungeon filed a complaint. About you.": "{user}, la mazmorra levantó una queja. Sobre ti.",
    "{user}, the tribe held a meeting. Without you. On purpose.": "{user}, la tribu tuvo una reunión. Sin ti. A propósito.",
    "{user}, the mountains declared you persona non grata.": "{user}, las montañas te declararon persona non grata.",
    "Luck went on a diet, {user}. You're not on the menu.": "La suerte se puso a dieta, {user}. No estás en el menú.",
    "Stars say: {user}, you'll fall. Beautifully, but painfully.": "Las estrellas dicen: {user}, te caerás. Bonito, pero doloroso.",
    "{user}, the tribe wrote a petition. Against you.": "{user}, la tribu escribió una petición. En tu contra.",
    "{user}, the mountains set a quota. For you — zero.": "{user}, las montañas pusieron una cuota. Para ti — cero.",
    "Luck says: {user}, it's not me, it's you.": "La suerte dice: {user}, no soy yo, eres tú.",
    "{user}, the caravan route changed. Now it goes past you.": "{user}, la ruta de la caravana cambió. Ahora pasa de largo.",
    "Stars whisper: {user}, a day of micro-disasters awaits.": "Las estrellas susurran: {user}, te espera un día de micro-desastres.",
    "{user}, the tribe changed the chat password.": "{user}, la tribu cambió la contraseña del chat.",
    "The oracle sees: {user}, you'll lose one sock. Your favorite one.": "El oráculo ve: {user}, perderás un calcetín. Tu favorito.",
    "Stars say: {user}, beware the fourth step.": "Las estrellas dicen: {user}, cuidado con el cuarto escalón.",
    "{user}, the mountains filed a complaint. In triplicate.": "{user}, las montañas levantaron una queja. Por triplicado.",
    "{user}, the caravan is empty. Because of you.": "{user}, la caravana está vacía. Por tu culpa.",
    "{user}, a pipirik-shaped cloud will appear at exactly 3:47 PM.": "{user}, una nube con forma de pipirik aparecerá exactamente a las 3:47 PM.",
    "{user}, your shadow is half a step behind. Wait for it to catch up.": "{user}, tu sombra va medio paso atrás. Espérala a que te alcance.",
    "{user}, the kettle will make a sound resembling your name.": "{user}, la tetera hará un sonido parecido a tu nombre.",
    "{user}, the cat outside knows your Wi-Fi password.": "{user}, el gato de afuera sabe tu contraseña del Wi-Fi.",
    "{user}, the dust under the bed isn't dust. It's sleeping mini-pipiriks.": "{user}, el polvo bajo la cama no es polvo. Son mini-pipiriks dormidos.",
    "The mug will turn its handle away from you, {user}. It's a rebellion.": "La taza girará su asa lejos de ti, {user}. Es una rebelión.",
    "{user}, a sock in the laundry will gain sentience. Briefly.": "{user}, un calcetín en la lavadora ganará conciencia. Brevemente.",
    "{user}, the tree in the yard will sigh at the sight of you.": "{user}, el árbol del patio suspirará al verte.",
    "The wall clock runs one second fast, {user}. Only for you.": "El reloj de pared va un segundo adelantado, {user}. Solo para ti.",
    "The bathroom faucet drips in Morse code, {user}. Decode it.": "La llave del baño gotea en código Morse, {user}. Descífralo.",
    "The trash can awaits you eagerly, {user}. Like a dog awaits its owner.": "El bote de basura te espera ansioso, {user}. Como un perro espera a su dueño.",
    "{user}, the spider in the corner is your personal biographer.": "{user}, la araña en la esquina es tu biógrafo personal.",
    "{user}, the bananas on the table approve of your choices.": "{user}, los plátanos en la mesa aprueban tus decisiones.",
    "The pencil in the drawer waits for you to write a masterpiece, {user}.": "El lápiz en el cajón espera que escribas una obra maestra, {user}.",
    "Today one of your fingers will be warmer than the rest, {user}. The pinkie.": "Hoy uno de tus dedos estará más caliente que los demás, {user}. El meñique.",
    "{user}, the clock will stop for exactly one second. In respect.": "{user}, el reloj se detendrá exactamente un segundo. Por respeto.",
    "The leaf on the sidewalk is an invitation, {user}. Pick it up and read.": "La hoja en la banqueta es una invitación, {user}. Recógela y lee.",
    "{user}, the downstairs neighbor will think of you. Kindly.": "{user}, el vecino de abajo pensará en ti. Amablemente.",
    "{user}, at the bottom of your pocket lies a coin from a past life.": "{user}, en el fondo de tu bolsillo hay una moneda de una vida pasada.",
    "Today street noise will form a melody, {user}. For 3 seconds.": "Hoy el ruido de la calle formará una melodía, {user}. Por 3 segundos.",
    "{user}, the street cat will blink its left eye. It's a code.": "{user}, el gato callejero parpadeará el ojo izquierdo. Es un código.",
    "{user}, the snowflake outside will be pipirik-shaped. If it's winter.": "{user}, el copo de nieve de afuera tendrá forma de pipirik. Si es invierno.",
    "A pebble on the sidewalk will roll away at the sight of you, {user}. Out of respect.": "Una piedrita en la banqueta rodará al verte, {user}. Por respeto.",
    "{user}, the grass outside grows toward your room.": "{user}, el pasto de afuera crece hacia tu cuarto.",
    "{user}, the floorboard will creak exactly three times. It's floor Morse code.": "{user}, la duela crujirá exactamente tres veces. Es código Morse del piso.",
    "{user}, the hanger in the closet is swaying. It's having fun.": "{user}, el gancho en el clóset se balancea. Se está divirtiendo.",
    "You'll see a bird with two shadows, {user}. This is normal.": "Verás un pájaro con dos sombras, {user}. Esto es normal.",
    "{user}, the tree shadow outside is dancing. Just for you.": "{user}, la sombra del árbol afuera está bailando. Solo para ti.",
    "{user}, chalk on the sidewalk wrote: 'Hi, {user}.' Or so it seems.": "{user}, el gis en la banqueta escribió: 'Hola, {user}.' O eso parece.",
    "Wind will carry the scent of vanilla, {user}. From nowhere.": "El viento traerá olor a vainilla, {user}. De la nada.",
    "{user}, the bookshelf will sigh. You'll hear it.": "{user}, el librero suspirará. Lo escucharás.",
    "The loose thread on your clothes is a guide thread, {user}. Follow it.": "El hilo suelto de tu ropa es un hilo guía, {user}. Síguelo.",
    "{user}, the scratch on the table is the Universe's autograph.": "{user}, el rayón en la mesa es el autógrafo del Universo.",
    "A soap bubble will orbit you twice, {user}. Not a coincidence.": "Una burbuja de jabón te orbitará dos veces, {user}. No es coincidencia.",
    "{user}, the napkin on the table is the Universe's white flag. It surrenders to you.": "{user}, la servilleta en la mesa es la bandera blanca del Universo. Se rinde ante ti.",
    "The glass on the table resonates with the Universe's frequency, {user}.": "El vaso en la mesa resuena con la frecuencia del Universo, {user}.",
    "{user}, the period at the end of a sentence isn't an end — it's a beginning.": "{user}, el punto al final de una oración no es un final — es un comienzo.",
    "A bird outside will sing F-sharp, {user}. That's your note.": "Un pájaro afuera cantará en Fa sostenido, {user}. Esa es tu nota.",
    "{user}, your hand shadow will draw a pipirik on the wall.": "{user}, la sombra de tu mano dibujará un pipirik en la pared.",
    "{user}, a stair step will creak a chord. A minor.": "{user}, un escalón crujirá un acorde. La menor.",
    "The coin in your pocket will warm up, {user}. It's thinking of you.": "La moneda en tu bolsillo se calentará, {user}. Está pensando en ti.",
    "{user}, the dewdrop on a leaf is a mirror to a parallel world.": "{user}, la gota de rocío en una hoja es un espejo a un mundo paralelo.",
    "{user}, the mark on the steamy glass is someone's greeting.": "{user}, la marca en el vidrio empañado es el saludo de alguien.",
    "{user}, the glint on the glass is a wink from a parallel reality.": "{user}, el brillo en el vidrio es un guiño de una realidad paralela.",
    "{user}, the bottle cap is a compass. Turn in its direction.": "{user}, la tapa de la botella es una brújula. Gira en su dirección.",
    "Today chalk will draw a perfect circle, {user}. It's a portal.": "Hoy el gis dibujará un círculo perfecto, {user}. Es un portal.",
    "Sound of waves — or the washing machine, {user}. You decide.": "Sonido de olas — o la lavadora, {user}. Tú decides.",
    "{user}, the tea will brew to exactly the right shade. It's an omen.": "{user}, el té quedará en el tono exacto. Es un presagio.",
    "A cloud will dissolve right above you, {user}. A portal opened and closed.": "Una nube se disolverá justo encima de ti, {user}. Un portal se abrió y cerró.",
    "{user}, the compass needle will tremble when you enter the room.": "{user}, la aguja de la brújula temblará cuando entres al cuarto.",
    "{user}, the wrinkle in the sheet is a contour map of adventures.": "{user}, la arruga en la sábana es un mapa de contorno de aventuras.",
    "{user}, the yellow autumn leaf is a receipt from the Universe. Keep it.": "{user}, la hoja amarilla de otoño es un recibo del Universo. Guárdala.",
    "The scratch on your nail is a symbol of change, {user}.": "El rayón en tu uña es un símbolo de cambio, {user}.",
    "{user}, the morning fog is a cloud that came down to look at you.": "{user}, la niebla matutina es una nube que bajó a verte.",
    "{user}, the button on your clothes is a tiny shield.": "{user}, el botón de tu ropa es un escudo diminuto.",
    "{user}, you're a hot shower after a tough day.": "{user}, eres una ducha caliente después de un día difícil.",
    "You're the one who remembers birthdays, {user}.": "Eres el que recuerda los cumpleaños, {user}.",
    "{user}, you're a song worth memorizing.": "{user}, eres una canción que vale la pena memorizar.",
    "You're the one who makes 'ordinary' feel 'special,' {user}.": "Eres quien hace que lo 'ordinario' se sienta 'especial', {user}.",
    "{user}, you're a rare coin in a world of fakes.": "{user}, eres una moneda rara en un mundo de falsificaciones.",
    "You're the one whose hugs are remembered, {user}.": "Eres a quien le recuerdan los abrazos, {user}.",
    "{user}, you're the taste of childhood.": "{user}, eres el sabor de la infancia.",
    "{user}, you're the sound of the surf that soothes.": "{user}, eres el sonido del oleaje que tranquiliza.",
    "{user}, you smell like coziness.": "{user}, hueles a comodidad.",
    "{user}, you're the one who remembers the little things.": "{user}, eres quien recuerda las cosas pequeñas.",
    "You're the definition of 'my person,' {user}.": "Eres la definición de 'mi persona', {user}.",
    "You're the one who carries an umbrella for others, {user}.": "Eres quien lleva paraguas para los demás, {user}.",
    "{user}, you're the finest exhibit in the museum of humanity.": "{user}, eres la pieza más fina del museo de la humanidad.",
    "You're the one who remembers what matters, {user}.": "Eres quien recuerda lo que importa, {user}.",
    "{user}, you're a soft landing after turbulence.": "{user}, eres un aterrizaje suave después de la turbulencia.",
    "You're the one who makes tea for others, {user}.": "Eres quien prepara el té para los demás, {user}.",
    "{user}, you're a cozy coffee corner in a noisy city.": "{user}, eres una acogedora esquina de café en una ciudad ruidosa.",
    "{user}, you're the silence of a library — calm and wise.": "{user}, eres el silencio de una biblioteca — calmo y sabio.",
    "You're the one who remembers their mom, {user}.": "Eres quien se acuerda de su mamá, {user}.",
    "You're warm water in the pool of life, {user}.": "Eres agua tibia en la piscina de la vida, {user}.",
    "You're the one who says 'I believe in you' and means it, {user}.": "Eres quien dice 'creo en ti' y lo dice en serio, {user}.",
    "{user}, you're the warm rug by the fireplace.": "{user}, eres el tapete cálido junto a la chimenea.",
    "You're someone's favorite scent, {user}.": "Eres el aroma favorito de alguien, {user}.",
    "{user}, you're described with the word 'genuine.'": "{user}, te describen con la palabra 'genuino'.",
    "You're a lamp that burns for others, {user}.": "Eres una lámpara que brilla para otros, {user}.",
    "{user}, you're morning porridge — simple but essential.": "{user}, eres avena de la mañana — simple pero esencial.",
    "{user}, you're someone's life preserver.": "{user}, eres el salvavidas de alguien.",
    "{user}, you're like a library — quiet, wise, free.": "{user}, eres como una biblioteca — silenciosa, sabia, gratis.",
    "You're the one who makes breakfast for others, {user}.": "Eres quien prepara el desayuno para los demás, {user}.",
    "{user}, you're a bedtime story for adults.": "{user}, eres un cuento de buenas noches para adultos.",
    "You're the one who picks up lost things, {user}.": "Eres quien recoge las cosas perdidas, {user}.",
    "You're the one who gives up your seat on the bus, {user}.": "Eres quien cede su asiento en el camión, {user}.",
    "{user}, you're a warm note in a pocket.": "{user}, eres una nota cálida en un bolsillo.",
    "{user}, you're a bridge that can bear any load.": "{user}, eres un puente que soporta cualquier carga.",
    "You're the one who waits without getting upset, {user}.": "Eres quien espera sin molestarse, {user}.",
    "{user}, you're a warm stone on the beach.": "{user}, eres una piedra cálida en la playa.",
    "{user}, you're a sip of water in the desert.": "{user}, eres un trago de agua en el desierto.",
    "You're the one who believes in fairy tales, {user}. And makes them real.": "Eres quien cree en los cuentos de hadas, {user}. Y los hace realidad.",
    "You're the one who finds the right words when needed, {user}.": "Eres quien encuentra las palabras correctas cuando se necesitan, {user}.",
    "{user}, you're the cozy sweater of a Sunday morning.": "{user}, eres el suéter acogedor de un domingo por la mañana.",
    "You're the warm breath of spring, {user}.": "Eres el aliento cálido de la primavera, {user}.",
    "{user}, you're someone's favorite character in real life.": "{user}, eres el personaje favorito de alguien en la vida real.",
    "{user}, you're the one who waters the neighbor's flowers.": "{user}, eres quien riega las flores del vecino.",
    "You're the hug nobody expected, {user}.": "Eres el abrazo que nadie esperaba, {user}.",
    "{user}, you're the tastiest line on life's menu.": "{user}, eres la línea más sabrosa del menú de la vida.",
    "{user}, you're a human blanket: warm, soft, needed.": "{user}, eres una cobija humana: cálida, suave, necesaria.",
    "{user}, you're the one who makes ordinary magical.": "{user}, eres quien hace lo ordinario mágico.",
    "You're a melody that gives goosebumps, {user}.": "Eres una melodía que da piel de gallina, {user}.",
    "{user}, you're the one who feeds birds in the park.": "{user}, eres quien alimenta a los pájaros en el parque.",
    "{user}, you're the one who warms with a single word.": "{user}, eres quien calienta con una sola palabra.",
    "You're the one who sees beauty in the ordinary, {user}.": "Eres quien ve la belleza en lo ordinario, {user}.",
    "{user}, you're the warmest room in the house.": "{user}, eres la habitación más cálida de la casa.",
    "{user}, you're the one worth trying harder for.": "{user}, eres por quien vale la pena esforzarse más.",
    "You're the kindest page in life's book, {user}.": "Eres la página más amable del libro de la vida, {user}.",
    "You're someone's guardian angel in regular clothes, {user}.": "Eres el ángel guardián de alguien con ropa normal, {user}.",
    "{user}, you're the universe's morning coffee.": "{user}, eres el café de la mañana del universo.",
    "You're the most needed person on the planet, {user}. For someone, definitely.": "Eres la persona más necesitada del planeta, {user}. Para alguien, definitivamente.",
    "{user}, you're the one people wait for.": "{user}, eres a quien la gente espera.",
    "You're the one who makes the world simpler and warmer, {user}.": "Eres quien hace el mundo más simple y cálido, {user}.",
    "You're living poetry, {user}.": "Eres poesía viviente, {user}.",
    "{user}, you're the one worth striving for.": "{user}, eres por quien vale la pena luchar.",
    "{user}, you're the most beautiful thought of the day.": "{user}, eres el pensamiento más hermoso del día.",
    "You're the one the world deserves, {user}.": "Eres quien el mundo merece, {user}.",
    "{user}, prediction: you'll be motivated exactly until the next TikTok.": "{user}, predicción: estarás motivado exactamente hasta el próximo TikTok.",
    "Oracle predicts: {user} promises to go to bed early. Again.": "El oráculo predice: {user} promete acostarse temprano. De nuevo.",
    "Stars whisper: {user}, you're an ideal. In a parallel universe.": "Las estrellas susurran: {user}, eres un ideal. En un universo paralelo.",
    "The oracle sees: {user}, you'll read a motivational quote. And lie down.": "El oráculo ve: {user}, leerás una frase motivacional. Y te acostarás.",
    "Prediction: {user} will assess their abilities. Incorrectly.": "Predicción: {user} evaluará sus habilidades. Incorrectamente.",
    "Oracle whispers: {user}, you're like chocolate — melts under pressure.": "El oráculo susurra: {user}, eres como el chocolate — se derrite bajo presión.",
    "Stars say: {user}, you're a walking motivational poster. Without the motivation.": "Las estrellas dicen: {user}, eres un póster motivacional caminante. Sin la motivación.",
    "{user}, prediction: you'll get a planner. For one day.": "{user}, predicción: comprarás una agenda. Para un día.",
    "The oracle sees: {user}, you're a professional. In the genre of doing nothing.": "El oráculo ve: {user}, eres un profesional. En el género de no hacer nada.",
    "{user}, the oracle sees your determination. It's flickering.": "{user}, el oráculo ve tu determinación. Parpadea.",
    "Oracle whispers: {user}, you're magnificent. When asleep.": "El oráculo susurra: {user}, eres magnífico. Cuando duermes.",
    "Prediction: {user} will text 'OMW' and take an hour to get ready.": "Predicción: {user} mandará un 'ya voy' y tardará una hora en prepararse.",
    "{user}, you're like Caps Lock — unexpected and annoying.": "{user}, eres como Bloq Mayús — inesperado y molesto.",
    "The oracle sees: {user}, you're a walking Wi-Fi zone. No password, no internet.": "El oráculo ve: {user}, eres una zona Wi-Fi caminante. Sin contraseña, sin internet.",
    "Oracle whispers: {user}, you're a perfect example of inconsistency.": "El oráculo susurra: {user}, eres un ejemplo perfecto de inconsistencia.",
    "{user}, you're like an ad — loud and unnecessary.": "{user}, eres como un anuncio — ruidoso e innecesario.",
    "Stars say: {user}, you're a walking paradox. Busy, but with nothing.": "Las estrellas dicen: {user}, eres una paradoja andante. Ocupado, pero con nada.",
    "{user}, prediction: you'll say 'in a minute.' That's a lie.": "{user}, predicción: dirás 'en un minuto'. Eso es mentira.",
    "{user}, the oracle drafted your horoscope. Deleted it. Felt sorry for you.": "{user}, el oráculo redactó tu horóscopo. Lo borró. Te tuvo lástima.",
    "Stars say: {user}, you're a master procrastinator. Even procrastinating the procrastination.": "Las estrellas dicen: {user}, eres un maestro procrastinador. Hasta procrastinas la procrastinación.",
    "Oracle whispers: {user}, you embody the phrase 'it'll be fine.'": "El oráculo susurra: {user}, encarnas la frase 'ya se arreglará'.",
    "The oracle sees: {user}, you're a source of inspiration. For those who want to know what not to do.": "El oráculo ve: {user}, eres una fuente de inspiración. Para los que quieren saber qué no hacer.",
    "{user}, you're like an antibiotic — helpful, but side effects.": "{user}, eres como un antibiótico — útil, pero con efectos secundarios.",
    "Stars whisper: {user}, you're a natural phenomenon. Pure laziness.": "Las estrellas susurran: {user}, eres un fenómeno natural. Pura flojera.",
    "Stars say: {user}, you're a special effect without a movie.": "Las estrellas dicen: {user}, eres un efecto especial sin película.",
    "{user}, the oracle sees: you're an encyclopedia of unkept promises.": "{user}, el oráculo ve: eres una enciclopedia de promesas incumplidas.",
    "Stars whisper: {user}, you're like a sticker — clingy, but not to the point.": "Las estrellas susurran: {user}, eres como una calcomanía — pegajoso, pero no del todo.",
    "Prediction: {user} will call mom. 'Later.'": "Predicción: {user} llamará a mamá. 'Luego'.",
    "{user}, you're like an empty file. Lots of space, little content.": "{user}, eres como un archivo vacío. Mucho espacio, poco contenido.",
    "Oracle whispers: {user}, you're magnificent in theory.": "El oráculo susurra: {user}, eres magnífico en teoría.",
    "The oracle sees: {user}, you're a living meme. Without the virality.": "El oráculo ve: {user}, eres un meme viviente. Sin la viralidad.",
    "Stars say: {user}, you're a talk show artist. Without an audience.": "Las estrellas dicen: {user}, eres un artista de talk show. Sin audiencia.",
    "{user}, prediction: you'll wash one plate and call it cleaning.": "{user}, predicción: lavarás un plato y lo llamarás limpieza.",
    "Oracle whispers: {user}, you're the king of promises. Without a kingdom.": "El oráculo susurra: {user}, eres el rey de las promesas. Sin un reino.",
    "{user}, you're like a screensaver — pretty, but does nothing.": "{user}, eres como un protector de pantalla — bonito, pero no hace nada.",
    "Prediction: {user} will drink a glass of water and feel healthy.": "Predicción: {user} tomará un vaso de agua y se sentirá saludable.",
    "{user}, the oracle read your skill résumé. Blank page.": "{user}, el oráculo leyó tu currículum de habilidades. Página en blanco.",
    "Stars whisper: {user}, you're a maestro of excuses.": "Las estrellas susurran: {user}, eres un maestro de las excusas.",
    "Prediction: {user} will go for a jog. Make it to the corner store.": "Predicción: {user} saldrá a correr. Llegará a la tienda de la esquina.",
    "The oracle sees: {user}, you're a model. Of how not to live.": "El oráculo ve: {user}, eres un modelo. De cómo no vivir.",
    "Oracle whispers: {user}, you're the hero of your own novel. An unreadable one.": "El oráculo susurra: {user}, eres el héroe de tu propia novela. Una ilegible.",
    "{user}, prediction: you'll forget why you came in. To life.": "{user}, predicción: olvidarás para qué entraste. A la vida.",
    "Stars whisper: {user}, you're like a 2010 smartphone — technically works.": "Las estrellas susurran: {user}, eres como un smartphone de 2010 — técnicamente funciona.",
    "{user}, you're the type who reads privacy policies. Just kidding.": "{user}, eres del tipo que lee las políticas de privacidad. Es broma.",
    "{user}, the oracle sees your schedule. Empty and proud.": "{user}, el oráculo ve tu agenda. Vacía y orgullosa.",
    "Stars say: {user}, you're a master of beginnings. Without endings.": "Las estrellas dicen: {user}, eres un maestro de los comienzos. Sin finales.",
    "Oracle whispers: {user}, you're a professional. In what — unclear, but a professional.": "El oráculo susurra: {user}, eres un profesional. ¿De qué? — no está claro, pero profesional.",
    "The oracle sees: {user}, you're a walking 'I'll finish it later.'": "El oráculo ve: {user}, eres un 'lo termino después' caminante.",
    "Stars whisper: {user}, you're an architect of castles in the air.": "Las estrellas susurran: {user}, eres un arquitecto de castillos en el aire.",
    "The oracle sees: {user}, you're like a screensaver — appear when nothing's happening.": "El oráculo ve: {user}, eres como un protector de pantalla — apareces cuando no pasa nada.",
    "Today it'll come from where you least expect, {user}.": "Hoy vendrá de donde menos lo esperas, {user}.",
    "Stars say: {user}, you're a walking disaster.": "Las estrellas dicen: {user}, eres un desastre andante.",
    "{user}, the pipirik lost interest in you. Completely.": "{user}, el pipirik perdió interés en ti. Completamente.",
    "Luck sent you a block, {user}. No reason given.": "La suerte te bloqueó, {user}. Sin razón dada.",
    "{user}, the dungeon prepared a double trap. Both yours.": "{user}, la mazmorra preparó una trampa doble. Las dos son tuyas.",
    "{user}, the pipirik filed a 3-page complaint.": "{user}, el pipirik presentó una queja de 3 páginas.",
    "{user}, the dungeon changed the password. Without notification.": "{user}, la mazmorra cambió la contraseña. Sin notificación.",
    "Stars say: {user}, you're a black cat to yourself.": "Las estrellas dicen: {user}, eres un gato negro para ti mismo.",
    "The oracle sees: {user}, you're target number one.": "El oráculo ve: {user}, eres el blanco número uno.",
    "{user}, the mountains are preparing an earthquake. Scale: {user}.": "{user}, las montañas preparan un terremoto. Escala: {user}.",
    "{user}, the caravan did a 180°. Reason: you.": "{user}, la caravana dio un giro de 180°. Razón: tú.",
    "Luck dialed your number, {user}. And hung up.": "La suerte marcó tu número, {user}. Y colgó.",
    "{user}, the pipirik went on vacation. From you.": "{user}, el pipirik se fue de vacaciones. De ti.",
    "Stars say: {user}, you're the epicenter of chaos. Involuntarily.": "Las estrellas dicen: {user}, eres el epicentro del caos. Involuntariamente.",
    "{user}, the mountains filed you under 'unwanted.'": "{user}, las montañas te archivaron como 'no deseado'.",
    "{user}, the dungeon filed a complaint to the heavens. About you.": "{user}, la mazmorra levantó una queja al cielo. Sobre ti.",
    "Luck marked you as spam, {user}.": "La suerte te marcó como spam, {user}.",
    "The oracle sees: {user}, you'll trip on air.": "El oráculo ve: {user}, tropezarás con el aire.",
    "{user}, the pipirik filed a lawsuit. Against you.": "{user}, el pipirik presentó una demanda. En tu contra.",
    "{user}, the mountains ordered an evacuation. Just for you.": "{user}, las montañas ordenaron una evacuación. Solo para ti.",
    "Luck declined your call, {user}. Three times in a row.": "La suerte rechazó tu llamada, {user}. Tres veces seguidas.",
    "{user}, the dungeon is mined. Address: {user}.": "{user}, la mazmorra está minada. Dirección: {user}.",
    "{user}, the caravan set up a barrier. Sign reads '{user} — stop.'": "{user}, la caravana puso una barrera. El letrero dice '{user} — alto'.",
    "{user}, the pipirik switched sides.": "{user}, el pipirik cambió de bando.",
    "Luck wrote an autobiography, {user}. Without you.": "La suerte escribió una autobiografía, {user}. Sin ti.",
    "{user}, the mountains closed the border. Using your photo.": "{user}, las montañas cerraron la frontera. Con tu foto.",
    "{user}, the dungeon renamed itself to 'Not for {user}.'": "{user}, la mazmorra se renombró a 'No para {user}'.",
    "Luck filed for divorce, {user}. Reason: incompatibility.": "La suerte pidió el divorcio, {user}. Razón: incompatibilidad.",
    "{user}, the pipirik blocked you. Even the pipirik.": "{user}, el pipirik te bloqueó. Hasta el pipirik.",
    "{user}, the mountains declared quarantine. From you.": "{user}, las montañas declararon cuarentena. De ti.",
    "Stars say: {user}, you're nature's one unfixable mistake.": "Las estrellas dicen: {user}, eres el único error incorregible de la naturaleza.",
    "{user}, the dungeon disabled gravity for you. You'll fall upward.": "{user}, la mazmorra desactivó la gravedad para ti. Caerás hacia arriba.",
    "{user}, the caravan rerouted. To another planet.": "{user}, la caravana cambió de ruta. A otro planeta.",
    "Luck printed your photo, {user}. Captioned: 'Do not serve.'": "La suerte imprimió tu foto, {user}. Subtítulo: 'No atender'.",
    "The oracle sees: {user}, you're the universe's experiment. A failed one.": "El oráculo ve: {user}, eres el experimento del universo. Uno fallido.",
    "{user}, the pipirik installed antivirus. Against you.": "{user}, el pipirik instaló antivirus. Contra ti.",
    "{user}, the mountains installed an alarm system. For your approach.": "{user}, las montañas instalaron un sistema de alarma. Para cuando te acerques.",
    "{user}, the dungeon called for backup. Because of you.": "{user}, la mazmorra pidió refuerzos. Por tu culpa.",
    "Luck moved to another continent, {user}. No forwarding address.": "La suerte se mudó a otro continente, {user}. Sin dirección de reenvío.",
    "{user}, the caravan issued a memo: '{user} — persona non grata.'": "{user}, la caravana emitió un memo: '{user} — persona non grata'.",
    "{user}, the pipirik put you on a 3-week ignore list.": "{user}, el pipirik te puso en la lista de ignorados por 3 semanas.",
    "{user}, the mountains compiled a blacklist. You're #1.": "{user}, las montañas compilaron una lista negra. Eres el #1.",
    "Luck turned off notifications, {user}. Permanently.": "La suerte desactivó las notificaciones, {user}. Permanentemente.",
    "{user}, the dungeon hung a portrait labeled 'entry forbidden.' The portrait is you.": "{user}, la mazmorra colgó un retrato con la leyenda 'entrada prohibida'. El retrato eres tú.",
    "{user}, the caravan left you nothing. Literally nothing.": "{user}, la caravana no te dejó nada. Literalmente nada.",
    "{user}, the pipirik wrote a will. You get the debts.": "{user}, el pipirik escribió un testamento. A ti te tocan las deudas.",
    "{user}, the mountains closed for eternal renovation. Cause: you.": "{user}, las montañas cerraron por remodelación eterna. Causa: tú.",
    "{user}, the caravan delivered fines. All for you.": "{user}, la caravana entregó multas. Todas para ti.",
    "Luck unfriended you, {user}. Long ago.": "La suerte te eliminó de amigos, {user}. Hace rato.",
    "The oracle sees: {user}, ahead is a dead end. No detour.": "El oráculo ve: {user}, adelante hay un callejón sin salida. Sin desvío.",
    "{user}, the mountains wrote a review: '{user} — 1 out of 10.'": "{user}, las montañas escribieron una reseña: '{user} — 1 de 10'.",
    "{user}, the dungeon offered a discount. On problems. For you.": "{user}, la mazmorra ofreció un descuento. En problemas. Para ti.",
    "{user}, the caravan filed you under 'high risk.'": "{user}, la caravana te archivó como 'alto riesgo'.",
    "Luck read your horoscope, {user}. Cried.": "La suerte leyó tu horóscopo, {user}. Lloró.",
    "Oracle whispers: {user}, your future is gray. Dark gray.": "El oráculo susurra: {user}, tu futuro es gris. Gris oscuro.",
    "{user}, the pipirik formed a union. Against you.": "{user}, el pipirik formó un sindicato. En tu contra.",
    "Stars say: {user}, you're a vortex for trouble.": "Las estrellas dicen: {user}, eres un vórtice de problemas.",
    "{user}, the mountains sent an avalanche. Delivered.": "{user}, las montañas mandaron una avalancha. Entregada.",
    "Luck compiled a report, {user}. 'Success' column: empty.": "La suerte compiló un reporte, {user}. Columna de 'Éxito': vacía.",
    "{user}, the caravan published memoirs: 'How We Avoided {user}.'": "{user}, la caravana publicó memorias: 'Cómo Evitamos a {user}'.",
    "{user}, the pipirik ran away. In an unknown direction.": "{user}, el pipirik se escapó. En dirección desconocida.",
    "{user}, the mountains held a conference: 'What to do about {user}?'": "{user}, las montañas celebraron una conferencia: '¿Qué hacer con {user}?'",
    "Oracle whispers: {user}, I'm actually embarrassed for you.": "El oráculo susurra: {user}, la verdad me da pena por ti.",
    "{user}, the caravan hired security. From you.": "{user}, la caravana contrató seguridad. Contra ti.",
    "Stars say: {user}, your horoscope is a black square.": "Las estrellas dicen: {user}, tu horóscopo es un cuadrado negro.",
    "{user}, the pipirik raised a flag: 'Not surrendering — leaving.'": "{user}, el pipirik levantó bandera: 'No me rindo — me voy'.",
    "{user}, the mountains issued a forecast: '100% {user}-dangerous.'": "{user}, las montañas emitieron un pronóstico: '100% {user}-peligroso'.",
    "{user}, the dungeon issued an ultimatum: 'Either {user} goes, or we do.'": "{user}, la mazmorra lanzó un ultimátum: 'O se va {user}, o nos vamos nosotros'.",
    "{user}, the crow on the wire is thinking about you. Third hour running.": "{user}, el cuervo en el cable está pensando en ti. Ya lleva tres horas.",
    "The spider in the corner is weaving a web shaped like a QR code, {user}.": "La araña en la esquina teje una telaraña con forma de código QR, {user}.",
    "{user}, the lamppost shadow gave you a thumbs up.": "{user}, la sombra del poste de luz te dio un pulgar arriba.",
    "The shoes in the hallway held a meeting, {user}. Decided you're okay.": "Los zapatos en la entrada tuvieron una junta, {user}. Decidieron que estás bien.",
    "{user}, the cheese in the fridge awaits you like a friend.": "{user}, el queso en el refri te espera como un amigo.",
    "The calendar page will tear off by itself, {user}. It got tired of waiting.": "La hoja del calendario se arrancará sola, {user}. Se cansó de esperar.",
    "{user}, the fly is buzzing Beethoven. Fifth Symphony.": "{user}, la mosca zumba Beethoven. Quinta Sinfonía.",
    "The water drop on the table is a map of Atlantis, {user}.": "La gota de agua en la mesa es un mapa de la Atlántida, {user}.",
    "{user}, the curtain sways in waltz rhythm.": "{user}, la cortina se mece al ritmo de un vals.",
    "The shoelace will tie a double knot, {user}. It's protection.": "La agujeta hará un nudo doble, {user}. Es protección.",
    "The cloud outside will freeze in the shape of a question mark, {user}.": "La nube afuera se congelará en forma de signo de interrogación, {user}.",
    "The sand in your shoe is a traveler's talisman, {user}.": "La arena en tu zapato es un talismán de viajero, {user}.",
    "{user}, the morning fog is a tablecloth for giants' breakfast.": "{user}, la niebla matutina es un mantel para el desayuno de gigantes.",
    "{user}, the crack in the glass is the wall's smile.": "{user}, la grieta en el vidrio es la sonrisa de la pared.",
    "The elevator sound is the building purring, {user}.": "El sonido del elevador es el edificio ronroneando, {user}.",
    "{user}, the paper cup is a hat for a mouse. A tiny one.": "{user}, el vaso de papel es un sombrero para un ratón. Uno pequeñito.",
    "{user}, the candle's flicker is the eye of an ancient guardian.": "{user}, el parpadeo de la vela es el ojo de un guardián antiguo.",
    "{user}, the butterfly in the park is an oracle in disguise.": "{user}, la mariposa en el parque es un oráculo disfrazado.",
    "{user}, the icicle outside is a magic wand.": "{user}, el carámbano de afuera es una varita mágica.",
    "{user}, pencil shavings are petals of a wooden flower.": "{user}, las virutas del lápiz son pétalos de una flor de madera.",
    "The hair tie is an amulet against the evil eye, {user}.": "La liga para el pelo es un amuleto contra el mal de ojo, {user}.",
    "{user}, the fork's shadow is Poseidon's tiny trident.": "{user}, la sombra del tenedor es el pequeño tridente de Poseidón.",
    "{user}, the bread crumb on the table is a meteorite in miniature.": "{user}, la miga de pan en la mesa es un meteorito en miniatura.",
    "The bubble in the paint is a time capsule, {user}.": "La burbuja en la pintura es una cápsula del tiempo, {user}.",
    "{user}, the wear on the couch is a trade route map for ants.": "{user}, el desgaste del sofá es un mapa de rutas comerciales de hormigas.",
    "{user}, the fabric scrap is a sail for the bathtub ship.": "{user}, el retazo de tela es una vela para el barco de la bañera.",
    "The steam cloud above the cup is a coffee ghost, {user}.": "La nube de vapor sobre la taza es un fantasma de café, {user}.",
    "{user}, the crease on the pillow is a map of the sleeping kingdom.": "{user}, la arruga en la almohada es un mapa del reino dormido.",
    "{user}, the fence shadow is the day's barcode.": "{user}, la sombra de la cerca es el código de barras del día.",
    "The acorn under the tree is nature's flash drive, {user}.": "La bellota bajo el árbol es la USB de la naturaleza, {user}.",
    "{user}, the bubble in chewing gum is a portal to childhood.": "{user}, la burbuja del chicle es un portal a la infancia.",
    "{user}, the crack on the sidewalk is the border between two kingdoms.": "{user}, la grieta en la banqueta es la frontera entre dos reinos.",
    "{user}, the stain on the wall is the Universe's abstract painting.": "{user}, la mancha en la pared es la pintura abstracta del Universo.",
    "{user}, the tumbleweed is a traveler without a passport.": "{user}, el arbusto rodante es un viajero sin pasaporte.",
    "{user}, the ring mark on the table is the table's seal of approval.": "{user}, la marca del anillo en la mesa es el sello de aprobación de la mesa.",
    "The jar lid is a palm-sized shield, {user}.": "La tapa del frasco es un escudo del tamaño de la palma, {user}.",
    "{user}, the paint drop on the floor is a tiny point of no return.": "{user}, la gota de pintura en el piso es un pequeño punto sin retorno.",
    "{user}, the chalk screech is the voice of the wall.": "{user}, el chirrido del gis es la voz de la pared.",
    "The water bubble on a leaf is a lens for reading the future, {user}.": "La burbuja de agua en una hoja es un lente para leer el futuro, {user}.",
    "The teapot's shadow is the silhouette of an elephant, {user}. Or a pipirik.": "La sombra de la tetera es la silueta de un elefante, {user}. O un pipirik.",
    "{user}, the daisy petal is an entry ticket to the fairy world.": "{user}, el pétalo de la margarita es un boleto de entrada al mundo de las hadas.",
    "{user}, the fuzz on your sleeve is a sleeping caterpillar.": "{user}, la pelusa en tu manga es una oruga dormida.",
    "{user}, the dent in the can is a dragon's claw print.": "{user}, la abolladura en la lata es la huella de garra de un dragón.",
    "{user}, the creak of the third floorboard from the left is 'welcome.'": "{user}, el crujido de la tercera duela desde la izquierda es 'bienvenido'.",
    "{user}, the piece of bark is a page from a wooden book.": "{user}, el trozo de corteza es una página de un libro de madera.",
    "The spider on the wall is a GPS navigator from another world, {user}.": "La araña en la pared es un navegador GPS de otro mundo, {user}.",
    "{user}, the latte art on your cappuccino is the day's prophecy.": "{user}, el arte latte en tu capuchino es la profecía del día.",
    "{user}, the echo in the empty room is the voice of furniture that used to be here.": "{user}, el eco en la habitación vacía es la voz de los muebles que antes estaban aquí.",
    "{user}, the morning frost is the night's gray hair.": "{user}, la escarcha matutina es la cana de la noche.",
    "The mouse rustle behind the wall is applause from a parallel reality, {user}.": "El susurro del ratón detrás de la pared es un aplauso de una realidad paralela, {user}.",
    "{user}, the ring mark from the glass is the orbit of a tiny planet.": "{user}, la marca del vaso es la órbita de un planeta diminuto.",
    "The leaf on the branch is the tree's palm, {user}. It's waving at you.": "La hoja en la rama es la palma del árbol, {user}. Te está saludando.",
    "{user}, the hiccup is the body's Morse code. Decode it.": "{user}, el hipo es el código Morse del cuerpo. Descífralo.",
    "The foil rustle is the laughter of metal, {user}.": "El crujido del aluminio es la risa del metal, {user}.",
    "{user}, the palm print on the steamy glass is a portal through time.": "{user}, la huella de la palma en el vidrio empañado es un portal a través del tiempo.",
    "{user}, the sound of dripping is a time counter. Countdown.": "{user}, el sonido del goteo es un contador de tiempo. Cuenta regresiva.",
    "The snowflake on your sleeve is a hello from the stratosphere, {user}.": "El copo de nieve en tu manga es un saludo desde la estratósfera, {user}.",
    "{user}, the veins on the leaf are the tree's circulatory map.": "{user}, las venas de la hoja son el mapa circulatorio del árbol.",
    "{user}, the dandelion puff is a micro-agent parachutist.": "{user}, el diente de león es un micro-agente paracaidista.",
    "The glint in your pupil is a reflection of a tiny universe, {user}.": "El brillo en tu pupila es el reflejo de un universo diminuto, {user}.",
    "{user}, the smell of wet asphalt is Planet Earth's cologne.": "{user}, el olor a asfalto mojado es la colonia del planeta Tierra.",
    "{user}, the wire's shadow is the horizon line of a tiny world.": "{user}, la sombra del cable es la línea del horizonte de un mundo diminuto.",
    "{user}, the dewdrop is a tear of the morning fairy.": "{user}, la gota de rocío es una lágrima del hada de la mañana.",
}
